/* ============================================================
 * Filament DB · 主流 3D 打印耗材对比库
 * 内容创建：舒舒（基于 DeepSeek Harness 构建）
 * 开源免费，仅供学习交流；转载数据请注明出处
 * 数据口径：所有数值为典型区间，来源见 meta.sources；
 * 每次数据更新都经过与上一版逐项复核（见 meta.corrections）。
 * ============================================================ */
window.FILAMENT_DATA = {
  meta: {
    updatedAt: "2026-08-15",
    sources: [
      { name: "Prusa 材料库（官方）", url: "https://help.prusa3d.com/materials" },
      { name: "Prusament 官方 TDS", url: "https://prusament.com/technical-data-sheets/" },
      { name: "Simplify3D 耗材指南", url: "https://www.simplify3d.com/resources/materials-guide/" },
      { name: "Polymaker 官方技术数据一览（打印件实测）", url: "https://wiki.polymaker.com/polymaker-wiki/polymaker-wiki-zh/polymaker-chan-pin/polymaker-filaments/technical-data-at-a-glance.md" },
      { name: "Polymaker PolyLite PC 官方 TDS V4（打印件实测）", url: "https://www.igo3d.com/mediafiles/Sonstiges/Polymaker/PolyLite%20PC/PolyLite_PC_TDS_V4.pdf" },
      { name: "Bambu Lab 官方 Wiki（材料）", url: "https://wiki.bambulab.com/zh/general/filament-guide-material-table" },
      { name: "eSUN 官方 TDS", url: "https://www.esun3d.com/uploads/eSUN_PLA-Filament_TDS_V4.0.pdf" },
      { name: "eSUN 官方材料页", url: "https://www.esun3d.com/filaments/" },
      { name: "Sunlu（三绿）官方", url: "https://www.sunlu.com/zh-cn/collections/all" },
      { name: "Kexcelled（诺思贝瑞）官方", url: "https://kexcelled3d.com" },
      { name: "FilamentHub TDS 汇总", url: "https://www.filamenthub.com.au/pages/filament-data" },
      { name: "All3DP 耗材指南", url: "https://all3dp.com/1/3d-printer-filament-types-3d-printing-3d-filament/" },
      { name: "NIOSH 3D 打印安全公告", url: "https://www.cdc.gov/niosh/bulletin/2018/3d-printing.html" }
    ],
    corrections: [
      {
        date: "2026-08-15",
        item: "PC（聚碳酸酯）力学数据口径",
        issue: "初稿按注塑级树脂数据填写（断裂伸长率 50–100%、缺口冲击 20–50 kJ/m²），与 3D 打印件实测严重不符",
        fix: "按 Polymaker PolyLite PC 官方 TDS（打印件实测：拉伸 62.7 MPa、伸长率 3.2%、Charpy 冲击 3.4 kJ/m²）矫正为 伸长率 3–15%、冲击 3–10 kJ/m²，并注明注塑级与打印件差异"
      },
      {
        date: "2026-08-15",
        item: "PPSU 玻璃化转变温度",
        issue: "初稿 Tg 185–190℃ 实为 PSU（聚砜）的值",
        fix: "矫正为 PPSU 正确值 215–225℃（Tg 随牌号 215–225℃）"
      },
      {
        date: "2026-08-15",
        item: "PEEK / PEKK / PA6 缺口冲击强度",
        issue: "初稿冲击值偏高（PEEK 20–40、PEKK 15–30、PA6 15–35 kJ/m²）",
        fix: "按注塑级干态典型值矫正：PEEK 4–10、PEKK 5–10、PA6 干态 5–12 kJ/m²，并注明吸湿后韧性上升"
      },
      {
        date: "2026-08-15",
        item: "PVDF 热变形温度",
        issue: "初稿 HDT 100–115℃ 偏高",
        fix: "矫正为 55–90℃（1.82MPa 载荷典型值），翘曲倾向由中矫正为高"
      },
      {
        date: "2026-08-15",
        item: "POM 打印温度与干燥",
        issue: "初稿打印温度 200–230℃ 偏窄、缺干燥建议",
        fix: "按 3DXTech/厂商数据矫正为 195–235℃，补充干燥 80–90℃/2–4h，并明确过热（约 240℃+）释放甲醛的安全警示"
      },
      {
        date: "2026-08-15",
        item: "PA-CF 合并区间（PA6-CF 与 PA12-CF）",
        issue: "初稿只按 PA6-CF 填写，区间偏窄",
        fix: "按两种基材合并矫正：Tm 175–225℃、HDT 90–190℃、拉伸 80–130 MPa、密度 1.08–1.40，注明差异"
      },
      {
        date: "2026-08-15",
        item: "品牌产品线核对",
        issue: "初稿部分品牌型号未经官方渠道确认（如 eSUN 的 ePOM/ePPS/ePEI、拓竹 PETG-T）",
        fix: "逐一对照品牌官网/官方 Wiki 矫正：删除无法确认的型号，补充官方在售系列（Kexcelled 官网确认为 kexcelled3d.com，诺思贝瑞；拓竹 30+ 品类；三绿含 PEEK；Polymaker 2024 年 PolyLite 更名 PolyMaker）"
      },
      {
        date: "2026-08-15",
        item: "PLA+ 韧性数据",
        issue: "初稿按普通 PLA 推断 PLA+ 缺口冲击 6–10 kJ/m²，明显偏低",
        fix: "按 Polymaker 官方打印件实测矫正：PolyLite PLA Pro 冲击 17.1 kJ/m²、PolyMax PLA 达 38.9 kJ/m²；拉伸同时修正为 40–55 MPa（韧性增强以强度为代价）"
      },
      {
        date: "2026-08-15",
        item: "PLA-CF 拉伸强度",
        issue: "初稿按「碳纤=更强」推断拉伸 80–110 MPa，与官方实测严重不符",
        fix: "矫正为 30–50 MPa（Polymaker PLA-CF 官方 31.2 MPa、拓竹约 37 MPa）：碳纤提升刚度但拉伸强度反而低于普通 PLA，并修正 HDT 为 54–65℃"
      },
      {
        date: "2026-08-15",
        item: "PETG / ABS / ASA 官方打印件数据",
        issue: "初稿 HDT 与冲击按注塑级或经验值填写",
        fix: "按 Polymaker 官方打印件实测矫正：PETG HDT 65–80℃、冲击 3–12 kJ/m²；ABS HDT 95–120℃、冲击 10–18 kJ/m²；ASA HDT 100–110℃、冲击 8–12 kJ/m²"
      },
      {
        date: "2026-08-15",
        item: "TPU 伸长率与密度",
        issue: "初稿伸长率 350–600%、密度 1.20–1.22",
        fix: "按 Polymaker PolyFlex TPU95 官方实测矫正：伸长率 400–600%（实测 551%）、密度 1.16–1.22（含 HF 高速版）"
      },
      {
        date: "2026-08-15",
        item: "PA-CF 耐热上限",
        issue: "初稿 HDT 上限 190℃",
        fix: "按 Fiberon PA6-CF20 官方 HDT（0.45MPa）215℃ 矫正为 90–215℃，注明 0.45MPa 载荷口径"
      },
      {
        date: "2026-08-15",
        item: "最终交叉验证（第二轮矫正）",
        issue: "首轮矫正后，与常规耗材子代理调研（eSUN/Prusament/Braskem 官方 TDS）再次逐项比对",
        fix: "再矫正 13 项：PP 缺口冲击 25–50→3–14 kJ/m²、翘曲中→高；PET 难度 2→4、翘曲低→高、HDT 65–115℃；TPU Tg -50～-30℃、伸长率 400–800%；PVB 冲击 3–6→7–10 kJ/m²；ABS HDT 80–120℃（标注载荷差异）、打印温度 220–270℃；ASA 拉伸 35–48 MPa；PVA Tg/Tm 按水解度修正、HDT 留空；HIPS 伸长率 30–60%；PETG 伸长率 5–50%（屈服 vs 断裂口径差异）；PLA/PETG/PVB 密度与打印温度按官方 TDS 微调"
      },
      {
        date: "2026-08-15",
        item: "第三轮扩充：新增 12 种耗材（常规 5 + 工程 7）",
        issue: "用户反馈耗材种类不足；初稿为 25 种",
        fix: "新增 PLA Silk、木质 PLA、TPE、PETG-CF、BVOH、PC-ABS、PA12-CF、PET-CF、PPS-CF、PPA-CF、PEBA、ASA-CF 共 12 种，其中 7 种直接采用 Polymaker 官方打印件实测数据（技术数据一览），PPA-CF 采用拓竹官方数据（弯曲强度 208 MPa、HDT 205℃），全部标注来源"
      },
      {
        date: "2026-08-15",
        item: "第三轮扩充：新增 5 个品牌（共 10 个）",
        issue: "用户反馈品牌较少；原为 5 个",
        fix: "新增 Prusament（捷克）、创想三维 Creality、纵维立方 Anycubic、Overture（美国）、3DXTech（美国工程料厂）；型号逐一核对官方渠道，排除第三方贴牌（如 Creality 店内 Soleyin）"
      },
      {
        date: "2026-08-15",
        item: "PPA-CF 数据矫正",
        issue: "初稿 HDT 150–200℃ 为经验估计",
        fix: "按拓竹官方 Wiki 实测矫正：弯曲强度 208 MPa（干态）、HDT 205℃（0.45MPa）、弯曲模量 9860 MPa，区间修正为 HDT 150–205℃、弯曲 150–210 MPa"
      },
      {
        date: "2026-08-15",
        item: "PET-CF 耐热口径矫正",
        issue: "不同厂商 HDT 口径差异大（拓竹 87℃ vs Polymaker 147.5℃）",
        fix: "注明口径：拓竹 PET-CF 87℃ 为未退火值，Polymaker PET-CF17 147.5℃ 为退火后值；数据表取 100–150℃ 并注明「退火才能获得高 HDT」"
      },
      {
        date: "2026-08-15",
        item: "交互升级与统计口径",
        issue: "新增综合评分、筛选、向导、最优高亮，需明确定义口径",
        fix: "综合评分 = 耐热(HDT)25% + 拉伸强度 25% + 抗冲击 20% + 打印易度 30%（满分 100）；表格 🏆 最优：数值列取区间中值比较（高者为优），难度/吸湿/翘曲/安全取低者为优；弹性体冲击「不断裂」不参与比较"
      },
      {
        date: "2026-08-15",
        item: "新材料交叉核验（第四轮矫正，官方 TDS 逐项比对）",
        issue: "新增 12 种材料的初稿值部分为经验估计，需与官方 TDS 逐项比对",
        fix: "按官方 TDS 矫正 30+ 项：PA12-CF 打印温度 280–300℃（原 250–290）、热床 40–60℃（原 80–110，Fiberon 低翘曲设计）；PPS-CF HDT 133–252.5℃（标注 0.45/1.8MPa 载荷差异）；PPA-CF 拉伸 120–170 MPa（拓竹官方 168±4）、Tm 255–265℃；PET-CF 热床 70–80℃、伸长率 2.4%；PC-ABS 打印温度 250–270℃、伸长率 4.2%、翘曲高；BVOH 密度 1.10–1.20、拉伸 20–45 MPa（Verbatim 参考）；PLA Silk 拉伸 30–45/冲击 3–14（eSUN 2.93 vs Polymaker 13.8 方法差异）；木质 PLA 冲击 4–16/吸湿高；PETG-CF 拉伸 50–63/冲击取缺口口径；TPE 打印 220–250℃/密度 1.10–1.20；PEBA 伸长率 400–900%、干燥 60℃/8h；ASA-CF 采用 Polymaker 官方（43.5/103/5.5）"
      },
      {
        date: "2026-08-15",
        item: "第八轮：新增 PETG-GF + 修正 PETG-CF 高速表述",
        issue: "1) 缺 PETG-GF 材料；2) 选材向导高速场景错误推荐 PETG-CF（碳纤增强流动性差，不支持高速打印）",
        fix: "新增 PETG-GF（Kexcelled K5/ELEGOO/Eryone 三品牌官方交叉：HDT 73–80℃/打印 230–280℃/拉伸 50–60 MPa/密度 1.30–1.35）；修正高速场景推荐（移除 PETG-CF，注明 CF/GF 系列不适合高速打印）"
      },
      {
        date: "2026-08-15",
        item: "第七轮：新材料子代理交叉验证矫正（4 种）",
        issue: "第六轮初稿基于主代理初步来源，子代理返回官方 TDS 交叉验证后需逐项矫正",
        fix: "PCTG：Tg 78–84℃/HDT 74–76℃/伸长率 100–340%（3D-Fuel 官方 220–340%，远超 PETG）/吸湿低；PA-GF：按 Fiberon PA6-GF25 TDS V1.1 矫正打印温度 270–300℃、床温 40–100℃（Warp-Free 工艺 40–50℃ 无腔体）、Tg 55–71℃、伸长 2–4%、难度 3、翘曲低；PEEK-CF：热端 360–450℃（原 360–400 不完整）、弯曲 130–150 MPa（原 180–220 错误）、HDT 265℃、翘曲高；PEEK-GF：官方型号为 FIBREX GF20（无 GF10）、HDT 300℃、弯曲 130–150、冲击官方未发布填 null"
      },
      {
        date: "2026-08-15",
        item: "第六轮（计划书阶段一）：新增 4 种耗材（37 → 41）",
        issue: "按完善计划书补全材料库：PCTG、PA-GF、PEEK-CF、PEEK-GF",
        fix: "PA-GF 采用 Polymaker Fiberon PA6-GF25 官方打印件实测（拉伸 80.1 MPa/HDT 191℃/冲击 10 kJ/m²）；PCTG 采用 3DXTech MAX-G 官方参数（250–270℃/无定形/耐化学优于 PETG）；PEEK-CF/GF 采用 3DXTech CarbonX 系列典型窗口（360–400℃/高温腔）并标注口径；PEEK-CF/GF 力学为典型区间待子代理返回后比对"
      },
      {
        date: "2026-08-15",
        item: "第五轮扩充：新增 7 个国产耗材品牌（10 → 17）",
        issue: "用户反馈需要更多国内品牌",
        fix: "新增爱乐酷 ELEGOO（深圳智能派）、Jayo（捷优，注册地香港）、FusRock（苏州复丝络科）、R3D（芜湖爱3迪科技）、爱丽滋 ALIZ（无锡，母公司江阴龙山）、彩多屋（惠州）、启庞 Kingroon（深圳）；品牌身份/官网/产品线经官方渠道核实：R3D 官网确认为 r3dprinter.com，爱丽滋官网为母公司 longshanplas.com/ALIZ/，Jayo 与创想三维无官方隶属关系、按独立品牌记录"
      },
      {
        date: "2026-08-17",
        item: "第九轮：新增 5 个国产耗材品牌（17 → 22）+ 12 条价格记录（75 → 87）",
        issue: "用户反馈需要更多品牌及其对应售价；新增品牌多无京东/天猫官方旗舰店，需如实标注渠道",
        fix: "新增艾普创（苏州，淘宝直营店+抖音商城，南极熊/搜狐/网易报道新品3件85折价：TPU 95A HS 92元/kg、PLA-CF 91.8元/kg、PPA-CF 310元/卷、PC-CF 238/PC-GF 187元/kg、PA6-CF 221/PA6-GF 195.5元/kg）、魔创（河南，1688批量直供哑光PLA/PETG低至20.4元/kg，行业文章口径并注明为批量价）、犀博（拼多多彩色PETG 17.68元，ZOL导购记录）、kaaber（PLA Basic约40元/卷为测评参考价，明确标注非活动记录）、以祥（东莞，打印派商城PLA 55.5/ABS 46.5元，克重未明确未折算）；所有非旗舰店条目已在平台列与note中如实标注来源类型（媒体报道/比价站/媒体导购/测评参考/第三方商城），未编造任何价格"
      }
    ],
    prices: {
      updatedAt: "2026-08-17",
      items: [
      {brand: "拓竹", material: "PLA", platform: "京东官方旗舰店", productName: "Bambu Lab PLA Basic基础RFID智能参数识别 净重1kg 红色10200 含料盘 1.75mm", listPrice: null, dealPrice: "56.88", pricePerKg: "56.88", lowestPrice: null, discount: "京东特价56.88元,可参加满1件8.5折/满3件8.7折", url: "http://m.guangdiu.com/detail.php?id=28722938", note: "逛丢聚合京东·拓竹官方旗舰店好价(2026-07-31);1kg/1.75mm含料盘", sourceType: "官方店铺"},
      {brand: "拓竹", material: "PLA", platform: "天猫官方旗舰店", productName: "拓竹 3D打印耗材PLA Basic 1.75mm 浅灰10104 无料盘 1kg", listPrice: "69.0", dealPrice: "50.98", pricePerKg: "50.98", lowestPrice: null, discount: "活动价69元,满3件打8.7折,3件实付152.95元,单件50.98元", url: "http://m.guangdiu.com/detail.php?id=25823921", note: "逛丢聚合天猫·拓竹官方旗舰店好价(2026-02-07);1kg/1.75mm无料盘", sourceType: "官方店铺"},
      {brand: "拓竹", material: "PLA", platform: "京东", productName: "Bambu Lab 拓竹 PLA Basic基础色高韧性易打印 净重1kg 白色10100 无料盘", listPrice: null, dealPrice: "49.05", pricePerKg: "49.05", lowestPrice: null, discount: "需用券49.05元", url: "https://www.smzdm.com/p/131444984/", note: "什么值得买京东优惠好价(2025年);具体店铺未核实,1kg/1.75mm无料盘", sourceType: "搜索摘要"},
      {brand: "拓竹", material: "PETG", platform: "天猫官方旗舰店", productName: "Bambu Lab 基础PETG Basic 3D打印耗材 强韧升级 1.75mm 1kg", listPrice: "51.0", dealPrice: "36.67", pricePerKg: "36.67", lowestPrice: null, discount: "活动价51元,满3件打8.7折+立减7.7元券,3件实付110.01元,单件36.67元", url: "http://m.guangdiu.com/detail.php?id=28858019", note: "逛丢聚合天猫·拓竹官方旗舰店好价(2026-08-09);1kg/1.75mm", sourceType: "官方店铺"},
      {brand: "拓竹", material: "PETG", platform: "京东官方旗舰店", productName: "Bambu Lab PETG Basic囤货套装六件套 净重6kg 无盘 RFID智能参数识别", listPrice: null, dealPrice: "177.11", pricePerKg: "29.52", lowestPrice: null, discount: "满1元打8.9折,6卷套装实付177.11元(折合约29.5元/kg)", url: "http://m.guangdiu.com/detail.php?id=28526745", note: "逛丢聚合京东·拓竹官方旗舰店好价(2026-07-20);6kg(6卷)无盘套装,折算29.52元/kg", sourceType: "官方店铺"},
      {brand: "拓竹", material: "ABS", platform: "天猫官方旗舰店", productName: "Bambu Lab 拓竹 3D打印耗材ABS超低气味高韧性耐热稳定 RFID 1KG 黑色40101 无料盘 1.75mm", listPrice: null, dealPrice: "49.63", pricePerKg: "49.63", lowestPrice: null, discount: "满3件打8.7折,3件实付148.89元,单件49.63元", url: "http://m.guangdiu.com/detail.php?id=24859637", note: "逛丢聚合天猫·拓竹官方旗舰店好价(2025-12-08);1kg/1.75mm无料盘", sourceType: "官方店铺"},
      {brand: "拓竹", material: "ASA", platform: "天猫官方旗舰店", productName: "Bambu Lab 拓竹 ASA 3D打印耗材 抗晒耐候抗高温 1kg 黑色45101", listPrice: null, dealPrice: "71.23", pricePerKg: "71.23", lowestPrice: null, discount: "立减14.9元+满3件打8.7折,3件实付213.69元,单件71.23元", url: "http://m.guangdiu.com/detail.php?id=24495154", note: "逛丢聚合天猫·拓竹官方旗舰店好价(2025-11-14);1kg/1.75mm;含料盘款曾84.1元(2025-07)", sourceType: "官方店铺"},
      {brand: "拓竹", material: "TPU 95A", platform: "京东官方旗舰店", productName: "拓竹 3D打印耗材 TPU for AMS(TPU 95A) 适配AMS多色高速打印 净重1kg 含料盘 1.75mm", listPrice: "146.0", dealPrice: "109.5", pricePerKg: "109.5", lowestPrice: null, discount: "活动价146元,满1件打8.5折,实付109.5元", url: "http://m.guangdiu.com/detail.php?id=26464891", note: "逛丢聚合京东·拓竹官方旗舰店好价(2026-03-22);TPU for AMS即拓竹TPU 95A,1kg含料盘", sourceType: "官方店铺"},
      {brand: "拓竹", material: "TPU 95A", platform: "天猫官方旗舰店", productName: "Bambu Lab 拓竹 TPU for AMS 3D打印耗材 黑色53101 无料盘 1kg", listPrice: null, dealPrice: "100.05", pricePerKg: "100.05", lowestPrice: null, discount: "满3件打8.7折,3件实付300.15元,单件100.05元", url: "http://m.guangdiu.com/detail.php?id=24380923", note: "逛丢聚合天猫·拓竹官方旗舰店好价(2025-11-08);1kg无料盘;含料盘款曾125.1元", sourceType: "官方店铺"},
      {brand: "拓竹", material: "PLA-CF", platform: "天猫精选", productName: "拓竹 PLA-CF 3D打印耗材 高强度碳纤维复合材料 RFID智能参数识别 1.75mm 1kg", listPrice: null, dealPrice: "147.26", pricePerKg: "147.26", lowestPrice: null, discount: "需买2件共294.52元,单件147.26元", url: "https://www.smzdm.com/p/85146070/", note: "SMZDM历史好价(约2023年,天猫精选),店铺未核实,价格较旧仅供参考", sourceType: "搜索摘要"},
      {brand: "拓竹", material: "PA-CF", platform: "京东官方旗舰店", productName: "拓竹 PAHT-CF 3D打印耗材 碳纤增强高温尼龙 黑色70100 净重1KG", listPrice: "457.3", dealPrice: "387.36", pricePerKg: "387.36", lowestPrice: null, discount: "3件8.7折,3件实付1162.08元,单件387.36元(降价前457.3元)", url: "http://m.guangdiu.com/detail.php?id=25828825", note: "逛丢聚合京东·拓竹官方旗舰店好价(2025-02-07);PAHT-CF即高温尼龙碳纤,1kg/1.75mm", sourceType: "官方店铺"},
      {brand: "拓竹", material: "PA-CF", platform: "京东官方旗舰店", productName: "Bambu Lab 拓竹 PA6-CF碳纤维增强尼龙6 黑色72100 净重0.5kg 含料盘", listPrice: "249.0", dealPrice: "173.4", pricePerKg: "346.8", lowestPrice: null, discount: "1件8.5折,实付173.4元(降价前249元)", url: "http://m.guangdiu.com/detail.php?id=23974499", note: "逛丢聚合京东·拓竹官方旗舰店好价(2025-10-17);实际规格0.5kg,折算346.8元/kg", sourceType: "官方店铺"},
      {brand: "拓竹", material: "PA-CF", platform: "官方渠道", productName: "拓竹PA6-CF碳纤维增强尼龙6 黑色72100 净重1kg 含料盘", listPrice: null, dealPrice: "336.6", pricePerKg: "336.6", lowestPrice: null, discount: "历史促销价336.6元(活动已结束)", url: "https://cu.manmanbuy.com/discuxiao_514303637.aspx", note: "慢慢买历史价格快照(已结束),平台未注明;1kg含料盘,与京东0.5kg价(346.8元/kg)互相印证", sourceType: "搜索摘要"},
      {brand: "Jayo", material: "PLA", platform: "天猫官方旗舰店", productName: "JAYO 3D打印耗材 PLA 1.75mm环保1kg整齐排线快速打印 黑色 1.1KG 无料盘", listPrice: "39.9", dealPrice: "29.9", pricePerKg: "27.18", lowestPrice: null, discount: "今日特价29.9元(降价前39.9元,限量200卷)", url: "http://m.guangdiu.com/detail.php?id=24756078", note: "逛丢聚合天猫·JAYO旗舰店好价(2025-12-01);实际规格1.1kg无料盘,折算27.18元/kg", sourceType: "官方店铺"},
      {brand: "Jayo", material: "PLA", platform: "天猫官方旗舰店", productName: "JAYO PLA Matte哑光 3D打印耗材 适用拓竹A1 P1 X H2D P2S H2S 哑光白 1.1KG 无料盘", listPrice: null, dealPrice: "32.9", pricePerKg: "29.91", lowestPrice: null, discount: "立减5.9元,到手32.9元", url: "http://m.guangdiu.com/detail.php?id=24222174", note: "逛丢聚合天猫·JAYO旗舰店好价(2025-10-31);PLA哑光款,1.1kg无料盘,折算29.91元/kg", sourceType: "官方店铺"},
      {brand: "Jayo", material: "PETG", platform: "天猫官方旗舰店", productName: "JAYO PETG耗材 3D打印机耗材 1.75mm FDM高透明度 无线盘PETG白色 1.1KG", listPrice: "34.99", dealPrice: "27.99", pricePerKg: "25.45", lowestPrice: null, discount: "活动价34.99元,立减7元券,实付27.99元", url: "http://m.guangdiu.com/detail.php?id=28549209", note: "逛丢聚合天猫·JAYO旗舰店好价(2026-07-22);规格1.1kg无料盘,折算25.45元/kg;6月同款26.59元", sourceType: "官方店铺"},
      {brand: "Jayo", material: "ABS", platform: "天猫官方旗舰店", productName: "JAYO 适用拓竹3d打印机ABS耗材 3.0高韧性环保 1.75mm 白色 1.1kg 含可拆料盘", listPrice: null, dealPrice: "38.6", pricePerKg: "35.09", lowestPrice: null, discount: "到手价38.6元", url: "http://m.guangdiu.com/detail.php?id=24504379", note: "逛丢聚合天猫·JAYO旗舰店好价(2025-11-15);标题1.1kg,折算35.09元/kg", sourceType: "官方店铺"},
      {brand: "eSUN", material: "PLA", platform: "天猫精选", productName: "易生 ESUN PLA Basic快速材料PLA-SS 3D打印耗材 1KG 1.75mm 黑色", listPrice: null, dealPrice: "37.3", pricePerKg: "37.3", lowestPrice: null, discount: "立减6.6元,到手37.3元", url: "https://guangdiu.com/search.php?q=esun", note: "逛丢聚合天猫好价(2025-11-11);店铺未在记录中注明(疑为esun旗舰店);1kg/1.75mm;另有2025-08-09同款39.1元记录", sourceType: "比价站"},
      {brand: "eSUN", material: "PLA", platform: "天猫精选", productName: "ESUN 易生 ePLA-Matte 3d打印机耗材 无卷盘 1.75mm", listPrice: "50.0", dealPrice: "44.39", pricePerKg: "44.39", lowestPrice: null, discount: "当前到手价44.39元,降价前售价50元,降幅11%", url: "https://guangdiu.com/search.php?q=esun", note: "逛丢聚合天猫好价(2025-11-07);PLA Matte无卷盘款,克重按1kg计(标题未注明,未完全确认)", sourceType: "比价站"},
      {brand: "eSUN", material: "ABS+", platform: "天猫精选", productName: "易生eSUN ABS+ 3D打印机耗材 出口包装1KG 1.75mm 黑色/灰色", listPrice: null, dealPrice: "46.32", pricePerKg: "46.32", lowestPrice: null, discount: "2件9折+售价立减9.3,2件实付92.64元,单件46.32元", url: "https://guangdiu.com/search.php?q=esun", note: "逛丢聚合天猫好价(2025-12-09);1kg/1.75mm(纸线盘/塑料盘混发)", sourceType: "比价站"},
      {brand: "eSUN", material: "PA-CF", platform: "官方渠道", productName: "ESUN/易生 PA-CF 尼龙碳纤维3D打印耗材 1.75mm*1kg", listPrice: "199.0", dealPrice: null, pricePerKg: "199.0", lowestPrice: null, discount: "起价199元(具体活动未注明)", url: "https://wiki.m.smzdm.com/list/k1k5z0v/", note: "什么值得买耗材百科'199元起'(共3款);平台未注明", sourceType: "搜索摘要"},
      {brand: "Kexcelled", material: "PETG", platform: "天猫精选", productName: "kexcelled THE K5 PETG 3D打印耗材(1.75mm,约1kg)", listPrice: null, dealPrice: "58.5", pricePerKg: "58.5", lowestPrice: null, discount: null, url: "https://www.smzdm.com/p/180087461/", note: "SMZDM促销帖含'58.5元',平台标注天猫精选,未能确认是否Kexcelled官方旗舰店;克重未明确,按K5 PETG常规1kg估算", sourceType: "搜索摘要"},
      {brand: "Kexcelled", material: "ABS", platform: "官方渠道", productName: "kexcelled THE K5 ABS 1.75mm 1kg 黑色", listPrice: null, dealPrice: "49.25", pricePerKg: "49.25", lowestPrice: null, discount: "实付246.25元购5件,折合49.25元/件(活动已结束)", url: "https://zhekou.manmanbuy.com/Sharedetailed_483524115.aspx", note: "慢慢买比价站促销页,规格1kg/1.75mm黑色;具体平台(京东/天猫)未注明", sourceType: "搜索摘要"},
      {brand: "Polymaker", material: "PLA", platform: "天猫官方旗舰店", productName: "Polymaker PolyLite 3D打印耗材PLA高性价比防堵头(1.75mm/1kg/1卷,白色)", listPrice: null, dealPrice: "68.0", pricePerKg: "68.0", lowestPrice: null, discount: "无券,日常到手价", url: "https://guangdiu.com/detail.php?id=20534433", note: "逛丢聚合天猫polymaker旗舰店报价(店铺名已验证),2024-11-10记录;数据较旧,仅作历史参考", sourceType: "官方店铺"},
      {brand: "Polymaker", material: "PLA", platform: "天猫官方旗舰店", productName: "Polymaker PolyTerra 3D打印耗材PLA高韧性易剥离(1.75mm/1kg,无盘碳墨黑)", listPrice: "59.0", dealPrice: "43.64", pricePerKg: "43.64", lowestPrice: null, discount: "立减7.1元+满3件打8.6折(3件起)", url: "https://guangdiu.com/detail.php?id=28858846", note: "逛丢聚合天猫polymaker旗舰店(店铺名已验证),2026-08-09记录,买3件实付43.64元/件", sourceType: "官方店铺"},
      {brand: "Polymaker", material: "PLA", platform: "天猫官方旗舰店", productName: "Polymaker PolyMax PLA 3D打印耗材(1.75mm,灰/黑)", listPrice: "196.0", dealPrice: "99.67", pricePerKg: null, lowestPrice: null, discount: "3件8折+售价立减20+满200减25元券,3件299.01元合99.67元/件", url: "https://guangdiu.com/detail.php?id=28963231", note: "逛丢聚合天猫polymaker旗舰店(店铺名已验证),2026-08记录;商品页未注明克重,pricePerKg未折算", sourceType: "官方店铺"},
      {brand: "Polymaker", material: "PETG", platform: "天猫官方旗舰店", productName: "Polymaker PolyLite 3D打印耗材PETG性能均衡(1.75mm/1kg)", listPrice: "89.0", dealPrice: "57.65", pricePerKg: "57.65", lowestPrice: null, discount: "满3件打7.5折+立减9.1元券,买3件实付低至57.65元/件", url: "https://guangdiu.com/detail.php?id=28562130", note: "逛丢聚合天猫polymaker旗舰店(店铺名已验证),2026-07-22记录,活动售价89元", sourceType: "官方店铺"},
      {brand: "Polymaker", material: "PETG", platform: "天猫官方旗舰店", productName: "Polymaker 高速PETG HF 3D打印机耗材线材(1.75mm/1kg)", listPrice: "47.8", dealPrice: "42.0", pricePerKg: "42.0", lowestPrice: null, discount: "立减5.8元券(1件可用)", url: "https://guangdiu.com/detail.php?id=28857859", note: "逛丢聚合天猫polymaker旗舰店(店铺名已验证),2026-08-09记录", sourceType: "官方店铺"},
      {brand: "Polymaker", material: "ABS", platform: "天猫官方旗舰店", productName: "Polymaker PolyLite ABS 超低气味3D打印耗材高韧性耐热(1.75mm/1kg)", listPrice: "61.4", dealPrice: "43.9", pricePerKg: "43.9", lowestPrice: null, discount: "首购-3券+立减9.3元+会员9折(券后43.9元)", url: "https://guangdiu.com/detail.php?id=24289798", note: "逛丢聚合天猫polymaker旗舰店(店铺名已验证),2025-11-03记录;正文注实付低至52.1元,两价并存以券后价为准", sourceType: "官方店铺"},
      {brand: "三绿", material: "PLA", platform: "天猫官方旗舰店", productName: "三绿SUNLU PLA Lite 易打印环保线材 高速打印 1.75mm", listPrice: null, dealPrice: "34.9", pricePerKg: "34.9", lowestPrice: null, discount: "领券1卷减11元(到手约34.9元/卷)", url: "https://detail.tmall.com/item.htm?id=965404835402", note: "购物党(gwdang)比价站抓取的天猫sunlu三绿旗舰店价格(2026-01-13);克重按1kg卷计(标题未注明,未完全确认)", sourceType: "搜索摘要"},
      {brand: "三绿", material: "PLA+", platform: "官方渠道", productName: "三绿 PLA+2.0 高韧性 FDM 3D打印耗材", listPrice: "49.9", dealPrice: null, pricePerKg: "49.9", lowestPrice: null, discount: "起价49.9元(具体活动未注明)", url: "https://wiki.m.smzdm.com/list/k1k5z0v/", note: "什么值得买耗材百科'49.9元起'(共3款);平台未注明", sourceType: "搜索摘要"},
      {brand: "三绿", material: "PLA+", platform: "官方渠道", productName: "三绿SUNLU 3D打印耗材 PLA+ 丝绸 PLA Silk+ 可控光泽 1.75mm", listPrice: null, dealPrice: "59.9", pricePerKg: "59.9", lowestPrice: null, discount: "活动实付(活动已结束)", url: "https://cu.manmanbuy.com/discuxiao_471079220.aspx", note: "慢慢买比价站历史活动实付价(已结束),京东/天猫具体平台未注明;克重按1kg计(未完全确认)", sourceType: "搜索摘要"},
      {brand: "三绿", material: "PETG", platform: "天猫精选", productName: "三绿 SUNLU 3D打印耗材PETG 基础色环保耐摔耐水 1kg线径1.75 白色无料盘", listPrice: null, dealPrice: "36.55", pricePerKg: "36.55", lowestPrice: null, discount: "立减6.6元+满3件打7.86折,3件实付109.65元,单件36.55元", url: "https://guangdiu.com/search.php?q=SUNLU%20PETG", note: "逛丢聚合天猫好价(2026年);1kg无料盘;店铺未在记录中注明(疑为三绿旗舰店)", sourceType: "比价站"},
      {brand: "爱乐酷", material: "PLA", platform: "天猫官方旗舰店", productName: "ELEGOO 3d打印耗材pla 1.75mm 3d打印机耗材料1kg FDM适用拓竹A1 P2S创想 纵维打印机", listPrice: "25.0", dealPrice: "20.0", pricePerKg: "20.0", lowestPrice: null, discount: "活动售价25元,立减3元券,实付20元", url: "https://guangdiu.com/detail.php?id=28858794", note: "逛丢聚合天猫·ELEGOO爱乐酷旗舰店(店铺名已在详情页确认),2026-08-09好价;标题含1kg,20元为史低价级别(谨慎采信)", sourceType: "官方店铺"},
      {brand: "爱乐酷", material: "PLA", platform: "天猫官方旗舰店", productName: "ELEGOO 3d打印耗材 金属pla耗材 1kg 1.75mm 适用拓竹A1 P2S创想 纵维打印机", listPrice: "69.0", dealPrice: "55.18", pricePerKg: "55.18", lowestPrice: null, discount: "活动售价69元,立减8.3元券,实付55.18元", url: "https://guangdiu.com/search.php?q=ELEGOO", note: "逛丢聚合ELEGOO爱乐酷旗舰店系列好价(2026-08-09);金属质感PLA,1kg/1.75mm", sourceType: "比价站"},
      {brand: "爱乐酷", material: "PLA", platform: "天猫官方旗舰店", productName: "ELEGOO 3d打印耗材PLA木质材料 1.75mm 1kg 适用拓竹A1 P2S创想 纵维打印机", listPrice: "79.0", dealPrice: "63.18", pricePerKg: "63.18", lowestPrice: null, discount: "活动售价79元,立减9.5元券,实付63.18元", url: "https://guangdiu.com/search.php?q=ELEGOO", note: "逛丢聚合ELEGOO爱乐酷旗舰店系列好价(2026-08-09);木质PLA,1kg/1.75mm", sourceType: "比价站"},
      {brand: "爱乐酷", material: "ABS", platform: "天猫官方旗舰店", productName: "ELEGOO 3d打印耗材ABS 1.75mm 1kg 适用拓竹A1 P2S创想 纵维打印机", listPrice: "62.0", dealPrice: "49.54", pricePerKg: "49.54", lowestPrice: null, discount: "活动售价62元,立减7.5元券,实付49.54元", url: "https://guangdiu.com/search.php?q=ELEGOO", note: "逛丢聚合ELEGOO爱乐酷旗舰店系列好价(2026-08-09);1kg/1.75mm", sourceType: "比价站"},
      {brand: "爱乐酷", material: "ASA", platform: "天猫官方旗舰店", productName: "ELEGOO 3d打印耗材ASA材料 1.75mm 1kg 适用拓竹 P2S创想 纵维打印机", listPrice: "69.0", dealPrice: "55.18", pricePerKg: "55.18", lowestPrice: null, discount: "活动售价69元,立减8.3元券,实付55.18元", url: "https://guangdiu.com/search.php?q=ELEGOO", note: "逛丢聚合ELEGOO爱乐酷旗舰店系列好价(2026-08-09);1kg/1.75mm", sourceType: "比价站"},
      {brand: "启庞", material: "PLA", platform: "天猫官方旗舰店", productName: "启庞 kingroon 3d打印耗材pla 无料盘1KG 1.75mm 适配竹子可拆卸料盘 黑色", listPrice: null, dealPrice: "37.44", pricePerKg: "37.44", lowestPrice: null, discount: "国家补贴9.7折起(减1.16元),到手37.44元", url: "https://guangdiu.com/detail.php?id=24607584", note: "逛丢聚合天猫好价(2025-11-22);1kg无料盘;店铺:天猫启庞旗舰店(详情页核实),2025-11-22活动,可能已结束", sourceType: "官方店铺"},
      {brand: "启庞", material: "PLA", platform: "天猫精选", productName: "启庞 3d打印耗材pla 高韧性渐变丝绸材料1KG 3D打印哑光pla耗材 无料盘 黑色", listPrice: null, dealPrice: "36.9", pricePerKg: "36.9", lowestPrice: null, discount: "促销到手36.9元", url: "https://guangdiu.com/search.php?q=jayo", note: "逛丢聚合天猫好价(2026-05-05);1kg无料盘", sourceType: "比价站"},
      {brand: "启庞", material: "PETG-CF", platform: "天猫官方旗舰店", productName: "启庞 kingroon 3d打印耗材 PETG碳纤维1.75mm混合线条 0.3KG 黑色", listPrice: null, dealPrice: "20.18", pricePerKg: "67.27", lowestPrice: null, discount: "立减4.2元+满28元减3元券,到手20.18元", url: "https://guangdiu.com/detail.php?id=24666053", note: "逛丢聚合天猫好价(2026年);实际规格0.3KG,折算67.27元/kg;店铺:天猫启庞旗舰店(详情页核实),2025-11-26活动;标题含1KG字样但SKU为0.3KG", sourceType: "官方店铺"},
      {brand: "创想三维", material: "PLA", platform: "官方渠道", productName: "创想三维 Soleyin Ultra PLA Matte哑光色 高韧高速 1.75mm 含料盘", listPrice: null, dealPrice: "45.5", pricePerKg: "45.5", lowestPrice: null, discount: "活动已结束45.5元", url: "https://zhekou.manmanbuy.com/Sharedetailed_503566060.aspx", note: "慢慢买比价站历史活动价(已结束);Soleyin为创想三维旗下耗材品牌;克重按1kg计", sourceType: "搜索摘要"},
      {brand: "创想三维", material: "PLA", platform: "创想三维官方商城(vip.creality.com)", productName: "创想三维 CR-PLA Matte 耗材 1.0kg 1.75mm", listPrice: "132.0", dealPrice: null, pricePerKg: "132.0", lowestPrice: null, discount: "官网商城零售价132元(经销商批发价另询)", url: "https://vip.creality.com/zh/goods-detail/1758", note: "创想三维官方商城(vip.creality.com)零售标价,非京东/天猫渠道;CR-PLA Matte 1.0kg/1.75mm,官方价显著高于电商活动价;京东/天猫官方店页面反爬无法直接核验;行业报道称国产原厂PLA 1kg报价多在50-80元(新快报2026-06-15)", sourceType: "官方店铺"},
      {brand: "纵维立方", material: "PLA", platform: "天猫精选", productName: "纵维立方 3D打印机PLA耗材线材FDM 纯PLA材料 1.75mm 高纯度1KG", listPrice: null, dealPrice: "34.3", pricePerKg: "34.3", lowestPrice: "29.0", discount: "淘金币可抵2.34元起,到手34.3元", url: "https://www.smzdm.com/p/180564258/", note: "SMZDM天猫精选好价帖;店铺未逐条核实;1kg/1.75mm;史低29元(慢慢买历史活动价,已结束,zhekou.manmanbuy.com/Sharedetailed_488988384.aspx);官方天猫店为anycubic.tmall.com", sourceType: "搜索摘要"},
      {brand: "纵维立方", material: "PETG", platform: "天猫精选", productName: "纵维立方 Anycubic PETG透明耗材 1.75mm 可拆卸盘 3D打印材料", listPrice: "49.0", dealPrice: "22.9", pricePerKg: "22.9", lowestPrice: null, discount: "活动售价49元,叠加淘金币,实付22.9元", url: "https://guangdiu.com/search.php?q=Anycubic%20PETG", note: "逛丢聚合天猫好价(2025-07-24);克重按1kg计(标题未注明,未完全确认)", sourceType: "比价站"},
      {brand: "纵维立方", material: "PETG", platform: "天猫精选", productName: "纵维立方 Anycubic 自研PETG耗材", listPrice: null, dealPrice: "25.0", pricePerKg: "25.0", lowestPrice: null, discount: "立减16元+3元券,限时到手25元/卷", url: "https://guangdiu.com/search.php?q=Anycubic%20PETG", note: "逛丢聚合天猫好价(2025-07-14);克重按1kg计(未注明)", sourceType: "比价站"},
      {brand: "纵维立方", material: "PETG", platform: "官方渠道", productName: "Anycubic/纵维立方 3D打印耗材PETG 1.75mm 白色1KG 可拆盘", listPrice: null, dealPrice: "38.32", pricePerKg: "38.32", lowestPrice: "38.32", discount: "3件实付114.96元,折合38.32元/件(活动已结束)", url: "https://zhekou.manmanbuy.com/Sharedetailed_488086277.aspx", note: "慢慢买比价站历史活动价(已结束);具体平台未注明;史低38.32元(即本次3件装活动价)", sourceType: "搜索摘要"},
      {brand: "彩多屋", material: "PLA+", platform: "京东", productName: "彩多屋3D打印机耗材PLA+不堵头 1.75mm(克重未注明)", listPrice: "36.0", dealPrice: "28.1", pricePerKg: null, lowestPrice: null, discount: "活动售价36元,下单实付28.1元", url: "https://www.smzdm.com/p/132832598/", note: "什么值得买/逛丢聚合京东优惠(2024-11-12);标题未注明克重(常规为1kg但未证实),pricePerKg未折算", sourceType: "比价站"},
      {brand: "彩多屋", material: "PLA", platform: "京东", productName: "彩多屋 PLA打印耗材 三色渐变 1kg 丝绸红蓝绿(1.75mm)", listPrice: "58.0", dealPrice: "53.0", pricePerKg: "53.0", lowestPrice: null, discount: "满6元减5元优惠券", url: "", note: "逛丢聚合京东商城优惠(2024-09-30);明确1kg装;另有同系列丝绸双色1kg紫金/蓝金券后50.75元记录", sourceType: "比价站"},
      {brand: "彩多屋", material: "PLA", platform: "天猫", productName: "CAILAB彩多屋3D打印耗材PLA丝绸单色 200g 1.75mm 亮金金", listPrice: "17.5", dealPrice: "15.4", pricePerKg: "77.0", lowestPrice: null, discount: "立减2.1元,到手15.4元", url: "", note: "逛丢天猫精选(2026-08-09);200g装按克重折算77元/kg;另有同店PLA彩虹丝绸渐变19.3元(22-2.7)、250g渐变18.7元记录", sourceType: "比价站"},
      {brand: "彩多屋", material: "PETG", platform: "天猫", productName: "彩多屋3D打印耗材PETG透明 200G 黑色G419(标题含1KG)", listPrice: "13.0", dealPrice: "11.0", pricePerKg: "55.0", lowestPrice: null, discount: "立减2元,到手11元(淘金币可再抵0.13元起)", url: "", note: "逛丢天猫精选(2026-06-20);标题标'1KG'但价格对应200G规格,按200g折算55元/kg,克重对应存疑;另有京东PETG 15.9元(2026-06)、天猫PETG透明14.9元(2025-11)记录", sourceType: "比价站"},
      {brand: "彩多屋", material: "PETG-CF", platform: "京东官方旗舰店", productName: "彩多屋3D打印耗材PETG-CF碳纤维增强 200g体验装 1.75mm 黑色GCF419", listPrice: null, dealPrice: "15.9", pricePerKg: "79.5", lowestPrice: null, discount: "现售价15.9元", url: "https://item.jd.com/1016319722832.html", note: "购物党gwdang/逛丢京东比价(2026-06-04更新);店铺为'彩多屋官方旗舰店'(官方渠道);200g体验装折算79.5元/kg", sourceType: "官方店铺"},
      {brand: "R3D", material: "PLA", platform: "天猫", productName: "R3D pla耗材 适用于拓竹3d打印通用pla 1.75mm 实重1KG", listPrice: "41.93", dealPrice: "36.83", pricePerKg: "36.83", lowestPrice: "34.87", discount: "领立减5.1元优惠券,实付36.83元", url: "https://guangdiu.com/detail.php?id=28562233", note: "逛丢天猫精选(2026-07-22,天天特卖工厂渠道);标题明确实重1KG/1.75mm;店铺名未经商品页直接确认;史低34.87元(2025-09-09,PLA哑光黑1kg青春版)", sourceType: "比价站"},
      {brand: "R3D", material: "PETG", platform: "天猫", productName: "R3D 耗材PETG 适用于拓竹 出口外贸PETG材质 1.75mm 1KG装", listPrice: "28.11", dealPrice: "23.59", pricePerKg: "23.59", lowestPrice: "11.77", discount: "立减3.4元+立减1.12元券,实付23.59元", url: "https://www.smzdm.com/p/152798571/", note: "逛丢/什么值得买天猫精选(2026-08-09);标题明确1KG装/1.75mm;店铺名未经直接确认;史低11.77元(2025-07-09支付宝天天秒杀,粉色),2025-08~11多次23.9元(白色1kg经济款)", sourceType: "比价站"},
      {brand: "R3D", material: "PETG", platform: "京东", productName: "R3D 耗材PETG 拓竹适用 出口外贸PETG材质 1.75mm PETG透明色", listPrice: "23.9", dealPrice: "20.9", pricePerKg: "20.9", lowestPrice: null, discount: "活动售价23.9元,用券可20.9元", url: "", note: "逛丢京东优惠(2024-05-25);标题规格截断'PETG 透明色 1'(疑为1kg),克重未完全确认", sourceType: "比价站"},
      {brand: "爱乐酷", material: "PLA+", platform: "官方渠道", productName: "ELEGOO RAPID PLA+/高速耗材 黑色 300g", listPrice: null, dealPrice: "25.54", pricePerKg: "85.13", lowestPrice: null, discount: "组合装实付127.7元,折合25.54元/件(300g)", url: "https://zhekou.manmanbuy.com/Sharedetailed_487390881.aspx", note: "慢慢买折扣记录(活动已结束),平台未标注;300g/件折算85.13元/kg", sourceType: "比价站"},
      {brand: "爱乐酷", material: "PETG", platform: "官方渠道", productName: "爱乐酷ELEGOO PETG耗材 1.75mm 1kg/卷", listPrice: null, dealPrice: "23.0", pricePerKg: "23.0", lowestPrice: null, discount: null, url: "https://post.smzdm.com/zz/p/al9rwgo8/", note: "SMZDM评测帖标题所示促销价(约23~25元/kg);平台未注明,推测为官方旗舰店促销;1kg/卷", sourceType: "搜索摘要"},
      {brand: "爱乐酷", material: "PLA", platform: "京东官方旗舰店", productName: "ELEGOO爱乐酷 3d打印耗材 PLA丝绸色套装礼盒 1.75mm 4kg(4卷)", listPrice: null, dealPrice: "269.0", pricePerKg: "67.25", lowestPrice: null, discount: "券后269元(参与每满300减40、满300减20等)", url: "https://guangdiu.com/detail.php?id=20797198", note: "逛丢聚合(2024-12-10,爱乐酷京东自营旗舰店开业同期),活动可能已结束;4kg套装折算67.25元/kg", sourceType: "官方店铺"},
      {brand: "启庞", material: "PLA", platform: "官方渠道", productName: "KINGROON启庞 PLA耗材 1kg 1.75mm(常规带盘)", listPrice: null, dealPrice: "59.0", pricePerKg: "59.0", lowestPrice: null, discount: null, url: "https://zhekou.manmanbuy.com/Sharedetailed_485057987.aspx", note: "慢慢买折扣记录(已结束实付59元),平台未标注;1kg/1.75mm常规带盘", sourceType: "比价站"},
      {brand: "启庞", material: "PLA", platform: "天猫官方旗舰店", productName: "启庞 3D打印机PLA丝绸耗材 双色/三色丝绸渐变 仿金属色 1.75mm 1kg", listPrice: null, dealPrice: "28.9", pricePerKg: "28.9", lowestPrice: null, discount: null, url: "https://guangdiu.com/detail.php?id=27137610", note: "逛丢聚合(2026-05-04);店铺:天猫启庞旗舰店(详情页核实);丝绸2色PLA 1kg,活动可能已结束", sourceType: "官方店铺"},
      {brand: "启庞", material: "PETG", platform: "京东官方旗舰店", productName: "kingroon 启庞 3d打印材料 petg耗材 灰色PETG 1.75mm 1KG", listPrice: null, dealPrice: "27.34", pricePerKg: "27.34", lowestPrice: null, discount: null, url: "https://guangdiu.com/detail.php?id=20730926", note: "逛丢聚合(2024-12-02);店铺:京东KINGROON旗舰店(详情页核实);1kg/1.75mm,活动可能已结束", sourceType: "官方店铺"},
      {brand: "启庞", material: "ABS", platform: "天猫官方旗舰店", productName: "启庞 kingroon 3d打印耗材ABS高韧性耐热 1.75mm 1KG 白色", listPrice: null, dealPrice: "32.4", pricePerKg: "32.4", lowestPrice: null, discount: "立减4.6元+国家补贴9.7折(减1元)", url: "https://guangdiu.com/detail.php?id=24528165", note: "逛丢聚合(2025-11-17);店铺:天猫启庞旗舰店(详情页核实);1kg/1.75mm,活动可能已结束", sourceType: "官方店铺"},
      {brand: "启庞", material: "PA", platform: "天猫官方旗舰店", productName: "启庞 3D打印耗材PA尼龙 1.75mm PA6材料 1kg(耐高温100度以上)", listPrice: null, dealPrice: "80.1", pricePerKg: "80.1", lowestPrice: null, discount: null, url: "https://guangdiu.com/detail.php?id=27137621", note: "逛丢聚合(2026-05-04);店铺:天猫启庞旗舰店(详情页核实);PA6尼龙(非碳纤版,供参考),1kg/1.75mm", sourceType: "官方店铺"},
      {brand: "创想三维", material: "PLA", platform: "官方渠道", productName: "创想三维 Ender-PLA 耗材 1.0kg 1.75mm(白色)", listPrice: null, dealPrice: "48.5", pricePerKg: "48.5", lowestPrice: "48.5", discount: "已结束活动:194元拍4件(合48.5元/件)", url: "https://cu.manmanbuy.com/discuxiao_12404908.aspx", note: "慢慢买历史优惠价,活动已结束;京东/天猫平台未明示;京东评论见官方店Ender-PLA约60元/卷(club.jd.com SKU 10072411318496)", sourceType: "比价站"},
      {brand: "创想三维", material: "PLA", platform: "官方渠道", productName: "创想三维 Hyper Series PLA 1.75mm 1kg(白色,高速)", listPrice: null, dealPrice: "51.35", pricePerKg: "51.35", lowestPrice: "51.35", discount: "已结束活动价", url: "https://zhekou.manmanbuy.com/Sharedetailed_485474632.aspx", note: "慢慢买历史优惠价(高速Hyper PLA),活动已结束;官方商城同款Hyper系列PLA 1kg挂牌204元(vip.creality.com/zh/goods-detail/1951),渠道价差大", sourceType: "比价站"},
      {brand: "创想三维", material: "PLA+", platform: "创想三维官方商城(vip.creality.com)", productName: "创想三维 Ender-PLA+ 耗材 1.75mm 1kg", listPrice: "160.0", dealPrice: null, pricePerKg: "160.0", lowestPrice: null, discount: null, url: "http://vip.creality.com/zh/goods-detail/1772", note: "官方直营商城零售价(1.75mm/1kg卷,净重1kg/2.2lb)", sourceType: "官方店铺"},
      {brand: "创想三维", material: "PETG", platform: "创想三维官方商城(vip.creality.com)", productName: "创想三维 CR-PETG 耗材 1.0kg 1.75mm", listPrice: "118.0", dealPrice: null, pricePerKg: "118.0", lowestPrice: null, discount: null, url: "http://vip.creality.com/zh/goods-detail/1786", note: "官方直营商城零售价;第三方B2B平台幺米Lab参考价88元(非官方渠道)", sourceType: "官方店铺"},
      {brand: "创想三维", material: "PETG", platform: "创想三维官方商城(vip.creality.com)", productName: "创想三维 Hyper PETG 1kg(1.75mm)", listPrice: "109.0", dealPrice: null, pricePerKg: "109.0", lowestPrice: null, discount: null, url: "http://vip.creality.com/zh/goods-detail/2234", note: "官方直营商城零售价(净重1kg,高速Hyper系列)", sourceType: "官方店铺"},
      {brand: "创想三维", material: "ABS", platform: "创想三维官方商城(vip.creality.com)", productName: "创想三维 CR-ABS 耗材 1.0kg 1.75mm", listPrice: "108.0", dealPrice: null, pricePerKg: "108.0", lowestPrice: null, discount: null, url: "http://vip.creality.com/zh/goods-detail/1785", note: "官方直营商城零售价(净重1kg)", sourceType: "官方店铺"},
      {brand: "创想三维", material: "ABS", platform: "创想三维官方商城(vip.creality.com)", productName: "创想三维 Hyper ABS 1kg(1.75mm)", listPrice: "149.0", dealPrice: null, pricePerKg: "149.0", lowestPrice: null, discount: null, url: "http://vip.creality.com/zh/goods-detail/2063", note: "官方直营商城零售价(净重1kg)", sourceType: "官方店铺"},
      {brand: "创想三维", material: "ASA", platform: "创想三维官方商城(vip.creality.com)", productName: "创想三维 HP ASA 1kg(1.75mm)", listPrice: "200.0", dealPrice: null, pricePerKg: "200.0", lowestPrice: null, discount: null, url: "http://vip.creality.com/zh/goods-detail/2131", note: "官方直营商城零售价(毛重1.29kg,按1kg卷计)", sourceType: "官方店铺"},
      {brand: "创想三维", material: "TPU 95A", platform: "创想三维官方商城(vip.creality.com)", productName: "创想三维 CR-TPU 3D耗材 1.0kg 1.75mm(邵氏95A)", listPrice: "168.0", dealPrice: null, pricePerKg: "168.0", lowestPrice: null, discount: null, url: "http://vip.creality.com/zh/goods-detail/1788", note: "官方直营商城零售价;官方材料指南确认CR-TPU为邵氏95A", sourceType: "官方店铺"},
      {brand: "创想三维", material: "PLA-CF", platform: "创想三维官方商城(vip.creality.com)", productName: "创想三维 Hyper PLA-CF 1kg 1.75mm", listPrice: "233.6", dealPrice: null, pricePerKg: "233.6", lowestPrice: null, discount: null, url: "http://vip.creality.com/zh/goods-detail/2134", note: "官方直营商城零售价(净重1KG,碳纤维PLA)", sourceType: "官方店铺"},
      {brand: "创想三维", material: "PETG-CF", platform: "创想三维官方商城(vip.creality.com)", productName: "创想三维 Hyper PETG-CF 1kg(1.75mm)", listPrice: "239.0", dealPrice: null, pricePerKg: "239.0", lowestPrice: null, discount: null, url: "http://vip.creality.com/zh/goods-detail/2514", note: "官方直营商城零售价(净重1kg)", sourceType: "官方店铺"},
      {brand: "创想三维", material: "PA-CF", platform: "创想三维官方商城(vip.creality.com)", productName: "创想三维 Hyper PA6-CF 1kg(1.75mm)", listPrice: "409.0", dealPrice: null, pricePerKg: "409.0", lowestPrice: null, discount: null, url: "http://vip.creality.com/zh/goods-detail/2442", note: "尼龙碳纤;同系列官方商城价:Hyper PA612-CF 469元、Hyper PAHT-CF 549元、PPA-CF 599元(均1kg)", sourceType: "官方店铺"},
      {brand: "艾普创", material: "TPU 95A", platform: "淘宝直营店", productName: "艾普创 TPU 95A HS 高速耐磨柔性线材（300mm/s）1kg/1.75mm", listPrice: null, dealPrice: "92.0", pricePerKg: "92.0", lowestPrice: null, discount: "新品3件85折大促,92元/kg一卷", url: "https://nanjixiong.com/forum.php?mod=viewthread&tid=175713", note: "南极熊报道(2025-06-19):艾普创淘宝直营店TPU 95A HS,300mm/s高速打印,8款国潮色,磨耗仅23mm3;1kg/1.75mm", sourceType: "媒体报道"},
      {brand: "艾普创", material: "PLA-CF", platform: "淘宝直营店", productName: "艾普创 PLA-CF 碳纤维线材（10款中国传统色,高速）1kg/1.75mm", listPrice: "108.0", dealPrice: "91.8", pricePerKg: "91.8", lowestPrice: null, discount: "新品期2个月3件折后91.8元/kg(原价108元/kg)", url: "https://nanjixiong.com/forum.php?mod=viewthread&tid=176013", note: "南极熊报道(2025-07-11):官方淘宝店+抖音商城;层间强度较友商提升38%,支持300mm/s,10款中国传统色", sourceType: "媒体报道"},
      {brand: "艾普创", material: "PPA-CF", platform: "淘宝直营店", productName: "艾普创 PPA-CF 碳纤增强聚邻苯二甲酰胺（弯曲250MPa）1kg", listPrice: null, dealPrice: "310.0", pricePerKg: "310.0", lowestPrice: null, discount: "新品3件85折,约310元/卷", url: "https://www.sohu.com/a/909293513_181700", note: "南极熊/搜狐报道(2025-06-30):PPA CF XY弯曲强度破250MPa、模量11GPa,长期耐热120℃+、短期峰值220℃,250mm/s高速打印", sourceType: "媒体报道"},
      {brand: "艾普创", material: "PC-CF", platform: "淘宝直营店", productName: "艾普创 PC-CF 纤维增强聚碳酸酯（超低吸水0.20%）1kg", listPrice: null, dealPrice: "238.0", pricePerKg: "238.0", lowestPrice: null, discount: "新品3件85折,折后238元/kg", url: "https://www.sohu.com/a/921269509_181700", note: "南极熊/搜狐报道(2025-08-06):官方淘宝店+抖音商城;无需腔体加热,开放A1涂胶可打,6款中国传统色", sourceType: "媒体报道"},
      {brand: "艾普创", material: "PC-GF", platform: "淘宝直营店", productName: "艾普创 PC-GF 玻纤增强聚碳酸酯 1kg", listPrice: null, dealPrice: "187.0", pricePerKg: "187.0", lowestPrice: null, discount: "新品3件85折,折后187元/kg", url: "https://www.sohu.com/a/921269509_181700", note: "南极熊/搜狐报道(2025-08-06):同系列PC GF,支持AMS/CFS自动进料", sourceType: "媒体报道"},
      {brand: "艾普创", material: "PA-CF", platform: "淘宝直营店", productName: "艾普创 PA6-CF 碳纤增强尼龙6（HDT 197℃,300mm/s）1kg", listPrice: null, dealPrice: "221.0", pricePerKg: "221.0", lowestPrice: null, discount: "新品3件85折,折后221元/kg", url: "https://m.163.com/dy/article/KD43CB25051186GP.html", note: "南极熊报道(2025-10-30):PA6 CF热变形温度197℃,涂胶后无需腔体加热,狂暴模式300mm/s", sourceType: "媒体报道"},
      {brand: "艾普创", material: "PA-GF", platform: "淘宝直营店", productName: "艾普创 PA6-GF 玻纤增强尼龙6（HDT 191℃）1kg", listPrice: null, dealPrice: "195.5", pricePerKg: "195.5", lowestPrice: null, discount: "新品3件85折,折后195.5元/kg", url: "https://m.163.com/dy/article/KD43CB25051186GP.html", note: "南极熊报道(2025-10-30):PA6 GF热变形温度191℃,黑/白/灰/红4色,冲击较友商倍数级提升", sourceType: "媒体报道"},
      {brand: "魔创", material: "PLA", platform: "1688", productName: "魔创 哑光 PLA 高纯度 3D 打印耗材（1688 批量直供）", listPrice: null, dealPrice: "20.4", pricePerKg: "20.4", lowestPrice: null, discount: "1688 批量直供价,低至20.4元/千克", url: "https://wiki.1688.com/zh/3d-printing-filament/WKfmd1tlr20mio", note: "1688行业wiki文章(2026-05-18):魔创/彩多屋等品牌哑光PLA/PETG批量直供低至20.4元/千克,具体型号未注明,为批量采购口径", sourceType: "比价站"},
      {brand: "犀博", material: "PETG", platform: "拼多多", productName: "犀博 彩色 PETG 3D 打印线材 1.75mm 韧性稳定 1kg", listPrice: "19.68", dealPrice: "17.68", pricePerKg: "17.68", lowestPrice: null, discount: "拼多多活动售价19.68元,下单1件实付低至17.68元", url: "https://oa.zol.com.cn/1083/10839374.html", note: "中关村在线导购(2025-11-18):犀博彩色PETG 1kg/1.75mm,拼多多实付17.68元", sourceType: "媒体导购"},
      {brand: "kaaber", material: "PLA", platform: "淘宝", productName: "Kaaber PLA Basic 入门级 3D 打印耗材（1kg 装）", listPrice: "40.0", dealPrice: "40.0", pricePerKg: "40.0", lowestPrice: null, discount: null, url: "https://post.smzdm.com/talk/p/avvlo384/", note: "什么值得买测评文章提及约40元/卷(1kg装)为参考价而非活动记录(2025);渠道未核实,以店铺实际售价为准", sourceType: "测评参考"},
      {brand: "以祥", material: "PLA", platform: "打印派商城", productName: "东莞以祥 3D 打印机 PLA 耗材 0.5/1KG 1.75/2.85/3.0mm", listPrice: null, dealPrice: "55.5", pricePerKg: null, lowestPrice: null, discount: null, url: "http://wap.dayinpai.com/product/detail/996018722166241", note: "打印派商城收录东莞以祥 PLA 0.5/1KG规格售价55.5元;克重未明确,pricePerKg未折算", sourceType: "第三方商城"},
      {brand: "以祥", material: "ABS", platform: "打印派商城", productName: "东莞以祥 进口 ABS 3D 打印耗材 1.75/2.85/3.00mm", listPrice: null, dealPrice: "46.5", pricePerKg: null, lowestPrice: null, discount: null, url: "http://wap.dayinpai.com/product/detail/405212190118008", note: "打印派商城收录东莞以祥进口ABS售价46.5元;克重未明确,pricePerKg未折算", sourceType: "第三方商城"}

    ],
      summary: "调研时间2026-08-17,覆盖17个品牌、87条价格记录,来源以逛丢/什么值得买/慢慢买等比价聚合站、官方旗舰店详情页、品牌官方直营渠道(淘宝直营店/抖音商城/1688/拼多多)与媒体报道为主(京东/天猫商品页反爬无法直接访问,数据为2024-2026年公开好价记录,部分活动已结束,实际以商品页为准)。【性价比排名·按PLA/PLA+/PETG/ABS日常券后价折算每kg均价,1kg基准(多件折扣已折算)】第一梯队(约17-39元/kg): 犀博(拼多多彩色PETG 17.68)、魔创(1688批量哑光PLA 20.4,批量口径)、Jayo(PLA 27.2/PETG 25.5/ABS 35.1,1.1kg装)、纵维立方(PLA 34.3/PETG 22.9-25)、R3D(PLA 36.8/PETG 23.6)、启庞(PLA 37.4/PETG 27.3/ABS 32.4);第二梯队(约40-50元/kg): 三绿(PLA Lite 34.9/PETG 36.6)、创想三维电商活动价(Ender-PLA 48.5/Hyper PLA 51.35/Soleyin 45.5)、eSUN(PLA Basic 37.3/ABS+ 46.3)、爱乐酷ELEGOO(PLA 20/ABS 49.5)、kaaber(PLA Basic约40,测评参考价)、拓竹(单卷PLA 49-57/PETG 36.7/ABS 49.6,6kg套装29.5元/kg为最优单价)、彩多屋(PLA+ 28.1,克重未证实);第三梯队(约50-62元/kg): Polymaker(PLA 43.6-68/PETG 42-57.7/ABS 43.9)、Kexcelled(PETG 58.5/ABS 49.3)、以祥(打印派商城PLA 55.5/ABS 46.5,克重未明确);特殊: 创想三维官方商城挂牌价显著更高(CR-PLA Matte 132/PLA+ 160/PETG 109-118/ABS 108-149/ASA 200/TPU 168/PLA-CF 233.6/PETG-CF 239/PA-CF 409),约为电商活动价的2-3倍,采购应走电商旗舰店活动;艾普创走工业级路线(淘宝直营店,新品3件85折): TPU 95A HS 92/PLA-CF 91.8/PPA-CF 310/PC-CF 238/PC-GF 187/PA6-CF 221/PA6-GF 195.5元/kg;FusRock国内无官方渠道。【价格区间观察】PLA/PLA+ 1kg券后20-69元(主流39-59元,低于30元/kg多为低质料,SMZDM提示;1688批量口径20.4元除外);PETG 17.68-58.5元(犀博拼多多17.68为媒体记录;创想三维官方商城109-118元);ABS 32.4-49.6元(官方商城108-149元;以祥46.5克重未明确);ASA 55-71元(创想三维官方商城200元);TPU 95A 92-110元(艾普创92元/kg为新品促销价;拓竹电商价100-110元;创想三维官方商城168元);PLA-CF 91.8元(艾普创新品价)-233.6元(创想三维官方商城);PA-CF 199元(eSUN)-409元(创想三维官方商城),拓竹PAHT-CF 387.36元、PA6-CF折算346.8元/kg、艾普创PA6-CF 221元;PPA-CF 310元(艾普创);PETG-CF 67-80元/kg(启庞0.3kg/彩多屋200g小规格;创想三维官方商城239元)。【优惠形式】多件折扣(满3件8折-8.7折)与立减券是主流,拓竹/Jayo/Polymaker多件价与单件价差距约20-40%;会员价(京东PLUS/88VIP)、国家补贴(9.5-9.7折)叠加常见;拓竹6kg囤货套装折算单价最低;艾普创新品期3件85折为官方直营口径。【数据说明】lowestPrice仅以下可查: R3D(PLA 34.87/PETG 11.77)、创想三维(Ender-PLA 48.5/Hyper PLA 51.35)、纵维立方(PLA 29/PETG 38.32),其余品牌未编造史低价;eSUN PLA+、爱丽滋、Kexcelled PLA等公开搜索无售价故置null(渠道存在但价格未披露);爱丽滋/启庞/彩多屋/R3D部分条目为小规格(200g/300g/0.3kg)或克重存疑记录,pricePerKg已按标注克重折算;以祥克重未明确未折算;kaaber约40元为测评参考价,采购前需复核规格与实时价。"
    },
  },

  /* ===================== 常规耗材区 ===================== */
  zones: [
    {
      id: "standard",
      name: "常规耗材",
      nameCn: "常规耗材区",
      desc: "普及度最高、多数家用/入门机型可直接打印的材料：PLA 家族、PETG、ABS、ASA、柔性 TPU 与支撑类材料。打印门槛低、性价比高，覆盖 90% 以上日常打印需求。",
      materials: [
        {
          id: "pla", nameCn: "PLA", nameEn: "Polylactic Acid", family: "PLA系",
          color: "#4f9cf9",
          tg: [55, 65], tm: [150, 180], hdt: [53, 65],
          printTemp: [190, 230], bedTemp: [45, 60],
          tensile: [45, 65], flexural: [60, 90], impact: [3, 6], impactUnit: "kJ/m²", elongation: [2, 15],
          density: [1.17, 1.25], hygroscopic: "低",
          difficulty: 1, warp: "低", enclosure: "否", drying: null,
          safetyLevel: 0, fumes: "乳酸类微量挥发物（基本无刺激性）",
          safetyNote: "PLA 主要释放乳酸与少量低分子挥发物，刺激性低，通常视为最安全的 FDM 耗材；仍建议保持基本通风。可生物降解（工业堆肥条件）。",
          applications: ["原型打样", "摆件/模型", "教学", "艺术装饰"],
          drawbacks: ["耐热差（60℃即软化）", "偏脆易断", "不耐紫外线"],
          note: "熔化温度区间取自不同牌号（无定形/半结晶混合），常见牌号 Tm 约 160–175℃。Polymaker PolyLite PLA 官方打印件：拉伸 52.3 MPa、缺口冲击 3.3 kJ/m²。",
          sources: [{ name: "Prusa 材料库", url: "https://help.prusa3d.com/materials" }]
        },
        {
          id: "pla-plus", nameCn: "PLA+", nameEn: "PLA Plus / PLA Pro", family: "PLA系",
          color: "#4f9cf9",
          tg: [55, 65], tm: [155, 180], hdt: [53, 65],
          printTemp: [190, 230], bedTemp: [45, 60],
          tensile: [40, 55], flexural: [60, 90], impact: [10, 25], impactUnit: "kJ/m²", elongation: [10, 30],
          density: [1.20, 1.25], hygroscopic: "低",
          difficulty: 1, warp: "低", enclosure: "否", drying: null,
          safetyLevel: 0, fumes: "乳酸类微量挥发物（基本无刺激性）",
          safetyNote: "PLA+ 通过共混改性提升韧性，释放物与 PLA 相当，安全性好。",
          applications: ["功能性原型", "外壳", "卡扣件", "教学"],
          drawbacks: ["耐热仍差", "不同品牌配方差异大"],
          note: "PLA+ 并非统一标准，各厂商改性配方不同。官方打印件实测（Polymaker）：PolyLite PLA Pro 拉伸 49.8 MPa、缺口冲击 17.1 kJ/m²；PolyMax PLA 冲击达 38.9 kJ/m²——高韧性版本的冲击可数倍于普通 PLA。",
          sources: [{ name: "eSUN 官方", url: "https://www.esun3d.com" }]
        },
        {
          id: "pla-cf", nameCn: "PLA-CF", nameEn: "PLA Carbon Fiber", family: "PLA系",
          color: "#4f9cf9",
          tg: [55, 65], tm: [160, 180], hdt: [54, 65],
          printTemp: [200, 230], bedTemp: [45, 60],
          tensile: [30, 50], flexural: [90, 130], impact: [4, 8], impactUnit: "kJ/m²", elongation: [1, 3],
          density: [1.25, 1.30], hygroscopic: "低",
          difficulty: 2, warp: "低", enclosure: "否", drying: "建议 50℃/4h",
          safetyLevel: 0, fumes: "乳酸类微量挥发物 + 碳纤维粉尘（打磨时）",
          safetyNote: "打印释放物与 PLA 相当；切割/打磨碳纤维件会产生导电粉尘，务必戴口罩并避免进入电子设备。",
          applications: ["轻量化结构件", "无人机部件", "表面质感件"],
          drawbacks: ["磨喷嘴（需硬化钢喷嘴）", "韧性下降更脆"],
          note: "碳纤维提升刚度、尺寸稳定性与表面质感，但拉伸强度反而低于普通 PLA（官方打印件：Polymaker PLA-CF 31.2 MPa，拓竹 PLA-CF 约 37 MPa），碳纤与 PLA 界面结合弱所致；韧性也低于 PLA+。",
          sources: [{ name: "Bambu Lab Wiki", url: "https://wiki.bambulab.com/en/filament" }]
        },
        {
          id: "petg", nameCn: "PETG", nameEn: "Glycol-modified PET", family: "PET系",
          color: "#22c3a6",
          tg: [75, 85], tm: null, hdt: [65, 80],
          printTemp: [230, 260], bedTemp: [60, 90],
          tensile: [38, 55], flexural: [55, 75], impact: [3, 12], impactUnit: "kJ/m²", elongation: [5, 50],
          density: [1.24, 1.30], hygroscopic: "中",
          difficulty: 2, warp: "低", enclosure: "否", drying: "建议 65℃/4–6h",
          safetyLevel: 0, fumes: "低挥发（微量酯类/乙醛）",
          safetyNote: "PETG 释放物少、刺激性低，被认为是安全的常用耗材；略微吸湿，受潮后打印易拉丝起泡。",
          applications: ["透明/半透明件", "食品接触容器", "外壳", "户外件"],
          drawbacks: ["拉丝较明显", "吸湿后表面起泡", "不耐长期紫外"],
          note: "常规 3D 打印用 PETG 为无定形共聚酯，Tm 一栏留空。官方打印件（Polymaker）：PolyLite PETG 拉伸 50.8 MPa、HDT 78℃、缺口冲击 2.6 kJ/m²；PolyMax PETG 冲击 11.6 kJ/m²。断裂伸长率不同 TDS 差异大（屈服值 3–5% vs 断裂值可达 50%+），取典型打印件区间。",
          sources: [{ name: "Prusa 材料库", url: "https://help.prusa3d.com/materials" }]
        },
        {
          id: "abs", nameCn: "ABS", nameEn: "Acrylonitrile Butadiene Styrene", family: "ABS/ASA",
          color: "#f9a54f",
          tg: [100, 108], tm: null, hdt: [80, 120],
          printTemp: [220, 270], bedTemp: [80, 110],
          tensile: [32, 47], flexural: [55, 75], impact: [10, 25], impactUnit: "kJ/m²", elongation: [3, 25],
          density: [1.03, 1.06], hygroscopic: "中",
          difficulty: 3, warp: "高", enclosure: "建议", drying: "建议 80℃/4h（受潮时）",
          safetyLevel: 1, fumes: "苯乙烯（Styrene）等",
          safetyNote: "ABS 打印时释放苯乙烯等挥发物，气味明显；务必在通风处打印，最好封闭腔体 + 活性炭过滤，长时间打印建议使用过滤器。",
          applications: ["外壳/结构件", "汽车内饰件", "耐用消费品", "模型"],
          drawbacks: ["翘曲明显", "有气味需通风", "层间附着需控温"],
          note: "苯乙烯已被列为可能致癌物（IARC 2B），建议儿童/孕妇远离打印区域。官方打印件（Polymaker）：PolyLite ABS 拉伸 33.4 MPa、HDT 100℃（0.45MPa）、缺口冲击 18 kJ/m²；eSUN ABS 标称 HDT 78℃（载荷未注明）。HDT 高度依赖测试载荷（0.45MPa 95–120℃ / 1.8MPa 78–90℃）。",
          sources: [{ name: "Prusa 材料库", url: "https://help.prusa3d.com/materials" }]
        },
        {
          id: "asa", nameCn: "ASA", nameEn: "Acrylonitrile Styrene Acrylate", family: "ABS/ASA",
          color: "#f9a54f",
          tg: [95, 108], tm: null, hdt: [93, 110],
          printTemp: [220, 260], bedTemp: [90, 110],
          tensile: [35, 48], flexural: [65, 80], impact: [10, 20], impactUnit: "kJ/m²", elongation: [9, 25],
          density: [1.05, 1.13], hygroscopic: "低",
          difficulty: 3, warp: "高", enclosure: "建议", drying: null,
          safetyLevel: 1, fumes: "苯乙烯类（较 ABS 略少）",
          safetyNote: "ASA 与 ABS 类似释放苯乙烯类挥发物，同样需要通风/封闭腔体；耐候性显著优于 ABS。",
          applications: ["户外件", "汽车外饰", "无人机外壳", "太阳能支架"],
          drawbacks: ["打印条件与 ABS 相近", "价格高于 ABS", "气味仍需注意"],
          note: "ASA 以丙烯酸酯替代丁二烯，耐紫外线与耐候性大幅提升，是 ABS 的户外升级版。官方打印件（Polymaker ASA）：拉伸 43.8 MPa、HDT 103℃、缺口冲击 10.3 kJ/m²。",
          sources: [{ name: "Prusa 材料库", url: "https://help.prusa3d.com/materials" }]
        },
        {
          id: "tpu", nameCn: "TPU 95A", nameEn: "Thermoplastic Polyurethane 95A", family: "柔性",
          color: "#c98bf9",
          tg: [-50, -30], tm: null, hdt: null,
          printTemp: [200, 250], bedTemp: [30, 60],
          tensile: [26, 40], flexural: null, impact: [35, 60], impactUnit: "kJ/m²(不断裂)", elongation: [400, 800],
          density: [1.16, 1.24], hygroscopic: "中",
          difficulty: 2, warp: "低", enclosure: "否", drying: "建议 55–65℃/4–8h",
          safetyLevel: 0, fumes: "微量异氰酸酯/多元醇挥发物",
          safetyNote: "TPU 释放物少，一般安全；异氰酸酯仅在严重过热时值得关注，保持基本通风即可。",
          applications: ["减震缓冲", "密封圈/垫", "手机壳", "可穿戴"],
          drawbacks: ["柔性材料需直驱挤出", "打印速度慢", "吸湿后性能下降"],
          note: "95A 指邵氏硬度；Tg 低于室温，故常温下呈弹性体。官方打印件（Polymaker PolyFlex TPU95）：断裂伸长率 551%（eSUN eTPU-95A 标称 ≥800%）。抗冲击常「不断裂」，数值仅供参考；弯曲强度对弹性体无意义故留空。",
          sources: [{ name: "Polymaker 官方", url: "https://polymaker.com/filaments/" }]
        },
        {
          id: "pet", nameCn: "PET", nameEn: "Polyethylene Terephthalate", family: "PET系",
          color: "#22c3a6",
          tg: [70, 80], tm: [245, 260], hdt: [65, 115],
          printTemp: [240, 280], bedTemp: [80, 90],
          tensile: [45, 65], flexural: [75, 90], impact: null, impactUnit: "kJ/m²", elongation: [20, 100],
          density: [1.30, 1.40], hygroscopic: "中",
          difficulty: 4, warp: "高", enclosure: "建议", drying: "建议 65℃/4–6h",
          safetyLevel: 0, fumes: "低挥发（微量乙醛）",
          safetyNote: "PET 释放物少、安全性好；结晶倾向使层间结合需较高腔温。",
          applications: ["透明容器", "耐化学件", "食品接触"],
          drawbacks: ["结晶收缩控制难", "市售牌号较少"],
          note: "PET 为半结晶材料，与 PETG 相比结晶度更高、更硬；结晶收缩导致翘曲与层裂，打印窗口窄，难度显著高于 PETG。退火（100–120℃）后 HDT 可从 65–75℃ 提升至 95–115℃。市售纯 PET 耗材较少，多为 rPET 或 PET-CF。",
          sources: [{ name: "FilamentHub TDS", url: "https://www.filamenthub.com.au/pages/filament-data" }]
        },
        {
          id: "pp", nameCn: "PP", nameEn: "Polypropylene", family: "烯烃",
          color: "#7fd6ff",
          tg: [-15, 0], tm: [160, 170], hdt: [85, 105],
          printTemp: [220, 270], bedTemp: [60, 100],
          tensile: [16, 35], flexural: null, impact: [3, 14], impactUnit: "kJ/m²", elongation: [50, 300],
          density: [0.89, 0.92], hygroscopic: "低",
          difficulty: 4, warp: "高", enclosure: "建议", drying: null,
          safetyLevel: 0, fumes: "低挥发",
          safetyNote: "PP 释放物少、安全性好，常用于食品容器；难点在粘附而非毒性。",
          applications: ["铰链/活页", "耐疲劳件", "化工容器", "食品相关件"],
          drawbacks: ["几乎不粘任何表面（需PP胶带/专用板）", "收缩率大", "易拉丝"],
          note: "密度 <1，可浮于水；难点在第一层粘附（需 PP 专用胶带/板）。收缩率大（1.5–2.5%）导致翘曲明显；断裂伸长率屈服值约 12%、断裂值可达数百%。",
          sources: [{ name: "Prusa 材料库", url: "https://help.prusa3d.com/materials" }]
        },
        {
          id: "pvb", nameCn: "PVB", nameEn: "Polyvinyl Butyral", family: "支撑/精饰",
          color: "#8b9dc3",
          tg: [65, 70], tm: null, hdt: [58, 65],
          printTemp: [200, 235], bedTemp: [70, 80],
          tensile: [45, 57], flexural: [70, 75], impact: [7, 10], impactUnit: "kJ/m²", elongation: [5, 50],
          density: [1.08, 1.12], hygroscopic: "中",
          difficulty: 2, warp: "低", enclosure: "否", drying: "建议 50–60℃/4h",
          safetyLevel: 0, fumes: "低挥发",
          safetyNote: "PVB 释放物少，安全性好；可用乙醇蒸汽抛光获得光滑表面。",
          applications: ["光滑外观件", "蒸汽抛光装饰件", "展示模型"],
          drawbacks: ["强度一般", "抛光需额外设备"],
          note: "Polymaker PolySmooth 即 PVB 材料。Prusament PVB 官方 TDS：拉伸屈服 50–57 MPa、夏比缺口冲击 7–10 kJ/m²、HDT 63℃（0.45MPa）。",
          sources: [{ name: "Polymaker 官方", url: "https://polymaker.com/filaments/" }]
        },
        {
          id: "hips", nameCn: "HIPS", nameEn: "High Impact Polystyrene", family: "支撑/精饰",
          color: "#8b9dc3",
          tg: [95, 105], tm: null, hdt: [85, 100],
          printTemp: [225, 270], bedTemp: [95, 115],
          tensile: [25, 40], flexural: [35, 50], impact: [6, 20], impactUnit: "kJ/m²", elongation: [30, 60],
          density: [1.03, 1.06], hygroscopic: "低",
          difficulty: 3, warp: "高", enclosure: "建议", drying: null,
          safetyLevel: 1, fumes: "苯乙烯（Styrene）",
          safetyNote: "HIPS 与 ABS 同为苯乙烯系，释放苯乙烯，需通风/封闭腔体；主要用作 ABS 的可溶性支撑（柠檬烯溶解）。",
          applications: ["ABS 可溶性支撑", "轻质件", "发泡效果件"],
          drawbacks: ["气味同 ABS", "单独使用场景少"],
          note: "与 ABS 配合使用，支撑可溶于柠檬烯（d-Limonene）。",
          sources: [{ name: "Prusa 材料库", url: "https://help.prusa3d.com/materials" }]
        },
        {
          id: "pva", nameCn: "PVA", nameEn: "Polyvinyl Alcohol", family: "支撑/精饰",
          color: "#8b9dc3",
          tg: [60, 85], tm: [180, 230], hdt: null,
          printTemp: [180, 230], bedTemp: [45, 65],
          tensile: [20, 30], flexural: null, impact: null, impactUnit: "kJ/m²", elongation: [20, 300],
          density: [1.23, 1.27], hygroscopic: "极高",
          difficulty: 3, warp: "低", enclosure: "否", drying: "必需 45–55℃/4–8h，密封防潮",
          safetyLevel: 0, fumes: "低挥发（水溶性材料）",
          safetyNote: "PVA 水溶性、无毒，是最安全的支撑材料之一；但极易吸湿，受潮后挤出冒泡断料。",
          applications: ["水溶性支撑", "复杂悬空结构", "双色打印"],
          drawbacks: ["极吸湿，需干燥箱+密封", "价格较高", "支撑强度低"],
          note: "与水溶性打印面配合使用效果最佳；部分牌号含硼交联结构。Tg/Tm 随水解度变化（88% 水解 Tg 60–70℃/Tm 180–200℃；完全水解 Tg 约 85℃/Tm 220–230℃），伸长率测试条件差异大（eSUN 标称 360%）。",
          sources: [{ name: "Prusa 材料库", url: "https://help.prusa3d.com/materials" }]
        },
        {
          id: "pla-silk", nameCn: "PLA Silk", nameEn: "Silk PLA（丝绸光泽）", family: "PLA系",
          color: "#4f9cf9",
          tg: [55, 65], tm: [150, 180], hdt: [50, 60],
          printTemp: [190, 230], bedTemp: [25, 60],
          tensile: [30, 45], flexural: [44, 70], impact: [3, 14], impactUnit: "kJ/m²", elongation: [5, 30],
          density: [1.20, 1.25], hygroscopic: "中",
          difficulty: 1, warp: "低", enclosure: "否", drying: "建议 50–55℃/6–8h",
          safetyLevel: 0, fumes: "乳酸类微量挥发物（与PLA相同）",
          safetyNote: "PLA Silk 为 PLA 与弹性体共混的改性料，释放物与普通 PLA 相当，安全性好；光泽对打印方向敏感。",
          applications: ["丝绸光泽装饰件", "展示模型", "礼品手办", "艺术摆件"],
          drawbacks: ["韧性低于普通 PLA", "光泽依赖打印方向与温度", "拉丝略多"],
          note: "官方实测：eSUN ePLA-Silk TDS 拉伸 32.5 MPa、Izod 缺口冲击 2.93 kJ/m²（X-Y）；Polymaker Panchroma Silk 冲击 13.8 kJ/m²——冲击差异为缺口/无缺口测试方法不同所致。",
          sources: [{ name: "Polymaker 官方技术数据一览", url: "https://wiki.polymaker.com/polymaker-wiki/polymaker-wiki-zh/polymaker-chan-pin/polymaker-filaments/technical-data-at-a-glance.md" }]
        },
        {
          id: "pla-wood", nameCn: "木质 PLA", nameEn: "Wood-Filled PLA", family: "PLA系",
          color: "#4f9cf9",
          tg: [55, 65], tm: [150, 180], hdt: [50, 60],
          printTemp: [200, 235], bedTemp: [55, 65],
          tensile: [30, 45], flexural: [50, 70], impact: [4, 16], impactUnit: "kJ/m²", elongation: [3, 10],
          density: [1.15, 1.25], hygroscopic: "高",
          difficulty: 2, warp: "低", enclosure: "否", drying: "建议 55–65℃/8h",
          safetyLevel: 0, fumes: "乳酸类微量挥发物 + 木粉烧焦气味",
          safetyNote: "木质 PLA 含 20–30% 木粉，打印时轻微木材烧焦气味，基本安全；打磨产生木粉粉尘，建议戴口罩。",
          applications: ["木纹外观装饰件", "模型底座与场景", "艺术摆件", "概念模型"],
          drawbacks: ["木粉易堵喷嘴（建议 0.5mm+ 硬化喷嘴）", "强度低于纯 PLA", "表面粗糙需打磨/上漆"],
          note: "木粉含量各品牌不一（常见 20–30%）。官方实测（eSUN PLA-Wood TDS，X-Y）：拉伸 39.7 MPa、Izod 缺口冲击 15.9 kJ/m²、HDT 50℃（0.45MPa）。",
          sources: [{ name: "All3DP", url: "https://all3dp.com/1/3d-printer-filament-types-3d-printing-3d-filament/" }]
        },
        {
          id: "tpe", nameCn: "TPE", nameEn: "Thermoplastic Elastomer (83A类)", family: "柔性",
          color: "#c98bf9",
          tg: null, tm: null, hdt: null,
          printTemp: [220, 250], bedTemp: [45, 60],
          tensile: [15, 50], flexural: null, impact: [40, 70], impactUnit: "kJ/m²(不断裂)", elongation: [400, 700],
          density: [1.10, 1.20], hygroscopic: "高",
          difficulty: 3, warp: "低", enclosure: "否", drying: "建议 55℃/4h",
          safetyLevel: 0, fumes: "微量异氰酸酯类/VOC（气味小）",
          safetyNote: "TPE 释放物少，一般安全；邵氏硬度约 83A–87A，比 TPU 95A 更软，必须直驱/近端挤出机+慢速打印。",
          applications: ["软质密封件", "减震缓冲", "可穿戴", "手机壳"],
          drawbacks: ["软料送料困难，需直驱低速", "易拉丝/堵头", "吸湿后表面变差"],
          note: "eSUN 官方 TDS（eFlex-TPU-87A / Elastic-TPE-83A）：注塑样条拉伸 52 MPa、断裂伸长 500%，打印件因层间结合显著更低；官方未公布 Tg/Tm/HDT。",
          sources: [{ name: "eSUN 官方", url: "https://www.esun3d.com/flexibility-elasticity/" }]
        },
        {
          id: "petg-cf", nameCn: "PETG-CF", nameEn: "Carbon Fiber PETG", family: "PET系",
          color: "#22c3a6",
          tg: [70, 80], tm: null, hdt: [65, 80],
          printTemp: [240, 270], bedTemp: [60, 90],
          tensile: [50, 63], flexural: [77, 95], impact: [4, 8], impactUnit: "kJ/m²", elongation: [4, 10],
          density: [1.25, 1.30], hygroscopic: "中",
          difficulty: 2, warp: "低", enclosure: "否", drying: "建议 65℃/4–8h",
          safetyLevel: 1, fumes: "低挥发 + 碳纤维粉尘（打磨时）",
          safetyNote: "释放物与 PETG 相当，建议通风；切割/打磨产生导电碳纤维粉尘，务必戴口罩、手套并远离电子设备。",
          applications: ["轻量化支架", "外壳结构件", "工业夹具", "无人机部件"],
          drawbacks: ["磨喷嘴（需硬化钢，HRC40+）", "比 PETG 脆", "表面哑光带纤维纹理"],
          note: "三产品官方交叉：Polymaker PETG-rCF08 拉伸 59.8/HDT 68.6、拓竹 PETG-CF 拉伸 59±4/HDT 74、eSUN ePETG-CF 拉伸 51.3/HDT 70；冲击方法差异大（缺口 4–5 vs 无缺口 41.2 kJ/m²），表内取缺口值。",
          sources: [{ name: "Polymaker 官方技术数据一览", url: "https://wiki.polymaker.com/polymaker-wiki/polymaker-wiki-zh/polymaker-chan-pin/polymaker-filaments/technical-data-at-a-glance.md" }]
        },
        {
          id: "petg-gf", nameCn: "PETG-GF", nameEn: "Glass Fiber PETG（玻纤增强）", family: "PET系",
          color: "#22c3a6",
          tg: [75, 80], tm: null, hdt: [73, 80],
          printTemp: [230, 280], bedTemp: [55, 85],
          tensile: [50, 60], flexural: [78, 85], impact: [4, 8], impactUnit: "kJ/m²", elongation: [2, 5],
          density: [1.30, 1.35], hygroscopic: "中",
          difficulty: 3, warp: "低", enclosure: "否", drying: "必需 60–70℃/6–8h",
          safetyLevel: 1, fumes: "微量 VOC + 玻纤粉尘",
          safetyNote: "PETG 基体气味低，主要风险是玻纤粉尘（断料/打磨/后处理时吸入有害）：需通风打印，打磨时佩戴防尘口罩+护目镜。",
          applications: ["电气外壳（玻纤不导电）", "工业工装/夹具", "承重抗弯结构件", "耐磨端子/连接器"],
          drawbacks: ["不适合高速打印（推荐 40–60mm/s，高速易堵头断料）", "玻纤磨喷嘴（须硬化钢 0.4mm+）", "表面哑光磨砂、无光泽"],
          note: "三品牌官方交叉：Kexcelled K5 PETG GF（HDT 74.4℃）、ELEGOO PETG-GF（官方宣传：弯曲 83 MPa、冲击 51.9 kJ/m² 无缺口、HDT 73.9℃）、Eryone PETG Fiberglass 官方 TDS 最全（Tg 75℃/HDT 80℃/拉伸 53.6 MPa/弯曲 78.5/伸长 1.9%/密度 1.33）。共同点：玻纤增强不适合高速打印，必须硬化喷嘴。",
          sources: [{ name: "ELEGOO PETG-GF 官方", url: "https://www.elegoo.com/blogs/3d-printer-user-guide/three-new-high-performance-fiber-reinforced-3d-printing-filaments-from-elegoo-petg-cf-petg-gf-and-paht-cf" }, { name: "Eryone PETG Fiberglass TDS", url: "https://de.eryone3d.com/products/petg-fiberglass-filament" }]
        },
        {
          id: "bvoh", nameCn: "BVOH", nameEn: "Butenediol Vinyl Alcohol", family: "支撑/精饰",
          color: "#8b9dc3",
          tg: [60, 75], tm: [170, 210], hdt: null,
          printTemp: [190, 220], bedTemp: [40, 70],
          tensile: [20, 45], flexural: [60, 75], impact: null, impactUnit: "kJ/m²", elongation: [9, 50],
          density: [1.10, 1.20], hygroscopic: "极高",
          difficulty: 2, warp: "中", enclosure: "否", drying: "必需 60℃/12h（Bambu AMS HT 官方），密封防潮",
          safetyLevel: 0, fumes: "低挥发（水溶性材料）",
          safetyNote: "BVOH 水溶性、无特殊毒性（非食品接触级）；加热可能释放微量乙酸/乙醛类分解物，常规通风即可。",
          applications: ["水溶性支撑（多材料兼容）", "复杂内腔结构", "多色打印"],
          drawbacks: ["极吸湿，开封即需干燥密封", "价格昂贵、溶解需数小时", "与部分材料（如PETG）配合效果不佳"],
          note: "Bambu 官方未发布完整 TDS：打印/干燥参数取自官方 Bambu Studio 配置（喷嘴 220℃、AMS HT 干燥 60℃×12h）；物性（密度 1.14、Tg 68℃、Tm 176℃、拉伸 45 MPa）为 Verbatim BVOH 官方 TDS 同类参考值。",
          sources: [{ name: "Bambu Lab Wiki", url: "https://wiki.bambulab.com/zh/filament/bvoh" }]
        }
      ]
    },

    /* ===================== 工程耗材区 ===================== */
    {
      id: "engineering",
      name: "工程耗材",
      nameCn: "工程耗材区",
      desc: "面向功能性/工业级应用的高性能材料：PC、PA（尼龙）家族、POM、PPS、PEEK、PEI 等。性能上限高，但对打印机（高温、封闭腔体）、干燥与后处理要求苛刻。",
      materials: [
        {
          id: "pc", nameCn: "PC", nameEn: "Polycarbonate", family: "PC",
          color: "#f9685f",
          tg: [145, 150], tm: null, hdt: [110, 140],
          printTemp: [250, 310], bedTemp: [90, 120],
          tensile: [55, 70], flexural: [80, 100], impact: [3, 10], impactUnit: "kJ/m²", elongation: [3, 15],
          density: [1.19, 1.21], hygroscopic: "高",
          difficulty: 4, warp: "中", enclosure: "建议", drying: "建议 80–100℃/4–8h",
          safetyLevel: 1, fumes: "高温下微量双酚A类/碳酸酯挥发物",
          safetyNote: "PC 打印温度高（250–310℃），释放物浓度高于 PLA/PETG，务必通风；双酚A（BPA）相关物在高温下值得关注，长时间打印建议加过滤。",
          applications: ["透明耐热件", "防弹级防护件", "机械结构件", "电气外壳"],
          drawbacks: ["吸湿极敏感", "层间结合需高温腔", "易开裂"],
          note: "PC 层间结合依赖腔温，低温打印件强度大幅下降。Polymaker PolyLite PC 实测（打印件）：拉伸 62.7 MPa、断裂伸长率仅 3.2%、缺口冲击 3.4 kJ/m²、Tg 约 113℃（共混配方），注塑级 PC 数值显著高于打印件。",
          sources: [{ name: "Prusa 材料库", url: "https://help.prusa3d.com/materials" }]
        },
        {
          id: "pa6", nameCn: "PA6", nameEn: "Nylon 6 / Polyamide 6", family: "尼龙PA",
          color: "#f2c94c",
          tg: [40, 60], tm: [220, 225], hdt: [55, 80],
          printTemp: [245, 290], bedTemp: [70, 110],
          tensile: [45, 70], flexural: [65, 90], impact: [5, 12], impactUnit: "kJ/m²", elongation: [20, 100],
          density: [1.12, 1.15], hygroscopic: "极高",
          difficulty: 4, warp: "中", enclosure: "建议", drying: "必需 80℃/4–8h，打印中防潮",
          safetyLevel: 1, fumes: "己内酰胺（Caprolactam）等",
          safetyNote: "PA6 打印释放己内酰胺（刺激性、需通风），吸湿后释放加剧；务必通风+干燥。",
          applications: ["齿轮", "卡扣", "耐磨滑动件", "工具手柄"],
          drawbacks: ["吸湿极快（数小时即受影响）", "需干燥箱", "层间强度一般"],
          note: "己内酰胺粉尘/蒸气对皮肤与呼吸道有刺激性，长期暴露需防护。干态缺口冲击低（5–12 kJ/m²），吸湿后韧性大幅上升。",
          sources: [{ name: "Prusa 材料库", url: "https://help.prusa3d.com/materials" }]
        },
        {
          id: "pa12", nameCn: "PA12", nameEn: "Nylon 12 / Polyamide 12", family: "尼龙PA",
          color: "#f2c94c",
          tg: [40, 55], tm: [175, 180], hdt: [40, 55],
          printTemp: [240, 280], bedTemp: [70, 110],
          tensile: [45, 55], flexural: [55, 70], impact: [6, 15], impactUnit: "kJ/m²", elongation: [50, 250],
          density: [1.00, 1.02], hygroscopic: "中",
          difficulty: 3, warp: "低", enclosure: "建议", drying: "建议 70–80℃/4–8h",
          safetyLevel: 0, fumes: "内酰胺类（较PA6少）",
          safetyNote: "PA12 释放物较 PA6 少但仍需通风；吸湿性显著低于 PA6，是尼龙家族中最好打印的品种之一。",
          applications: ["柔性耐疲劳件", "卡扣/铰链", "精密齿轮", "运动器材"],
          drawbacks: ["强度低于 PA6", "价格较高", "仍需防潮"],
          note: "PA12 尺寸稳定性与低吸湿性优于 PA6，适合精细件。",
          sources: [{ name: "Prusa 材料库", url: "https://help.prusa3d.com/materials" }]
        },
        {
          id: "pa66", nameCn: "PA66", nameEn: "Nylon 66 / Polyamide 66", family: "尼龙PA",
          color: "#f2c94c",
          tg: [50, 70], tm: [255, 265], hdt: [75, 90],
          printTemp: [270, 300], bedTemp: [90, 120],
          tensile: [50, 80], flexural: [80, 100], impact: [4, 10], impactUnit: "kJ/m²", elongation: [20, 60],
          density: [1.13, 1.15], hygroscopic: "极高",
          difficulty: 5, warp: "高", enclosure: "必需", drying: "必需 80℃/4–8h",
          safetyLevel: 1, fumes: "己内酰胺等内酰胺类",
          safetyNote: "PA66 打印温度高、释放物需通风处理；吸湿同样极快。",
          applications: ["高强度结构件", "高温耐磨齿轮", "汽车件"],
          drawbacks: ["打印温度高", "极吸湿", "需硬化钢喷嘴"],
          note: "PA66 强度与耐热高于 PA6，但打印条件更苛刻，市售耗材较少；多数数据源于注塑级树脂，打印件强度通常更低。",
          sources: [{ name: "All3DP", url: "https://all3dp.com/1/3d-printer-filament-types-3d-printing-3d-filament/" }]
        },
        {
          id: "pa-cf", nameCn: "PA-CF", nameEn: "Carbon Fiber Reinforced Nylon", family: "尼龙PA",
          color: "#f2c94c",
          tg: [40, 60], tm: [175, 225], hdt: [90, 215],
          printTemp: [250, 300], bedTemp: [80, 120],
          tensile: [80, 130], flexural: [120, 200], impact: [3, 10], impactUnit: "kJ/m²", elongation: [2, 15],
          density: [1.08, 1.40], hygroscopic: "极高",
          difficulty: 4, warp: "低", enclosure: "建议", drying: "必需 80–90℃/4–8h",
          safetyLevel: 1, fumes: "己内酰胺 + 碳纤维粉尘",
          safetyNote: "PA-CF 兼具尼龙释放物与碳纤维粉尘问题：打印需通风，打磨需口罩；同时必须使用硬化钢/红宝石喷嘴。",
          applications: ["无人机结构件", "汽车轻量化件", "高强度支架", "工业夹具"],
          drawbacks: ["磨喷嘴", "极吸湿", "价格高"],
          note: "数值为 PA6-CF 与 PA12-CF 合并区间：PA6-CF（如拓竹 PAHT-CF、Polymaker Fiberon PA6-CF20）Tm 约 220–225℃、HDT 0.45MPa 约 190–215℃、拉伸 100–130 MPa；PA12-CF（Fiberon PA12-CF10）Tm 约 175–180℃、HDT 约 131℃、拉伸约 77 MPa。翘曲：PA12-CF 更低，PA6-CF 中等。",
          sources: [{ name: "Bambu Lab Wiki", url: "https://wiki.bambulab.com/en/filament" }]
        },
        {
          id: "pom", nameCn: "POM", nameEn: "Polyoxymethylene / Acetal", family: "POM",
          color: "#7fd6ff",
          tg: [-60, -30], tm: [165, 175], hdt: [100, 110],
          printTemp: [195, 235], bedTemp: [90, 120],
          tensile: [45, 70], flexural: [70, 100], impact: [5, 8], impactUnit: "kJ/m²", elongation: [15, 75],
          density: [1.40, 1.42], hygroscopic: "低",
          difficulty: 4, warp: "高", enclosure: "建议", drying: "建议 80–90℃/2–4h",
          safetyLevel: 2, fumes: "甲醛（Formaldehyde）",
          safetyNote: "POM 高温分解会释放甲醛（致癌物），打印时务必强通风/过滤，避免长时间过热喷嘴；这是 POM 打印最重要的安全点。",
          applications: ["齿轮", "轴承/滑轮", "卡扣", "精密传动件"],
          drawbacks: ["收缩/翘曲大", "高温释放甲醛", "粘附性差"],
          note: "POM 自润滑、耐磨，是传动件首选；但过热（约 240℃以上）会快速降解释放甲醛，必须控制温度。均聚/共聚熔点略有差异（165–175℃）。",
          sources: [{ name: "Filament Cheat Sheet", url: "https://filamentcheatsheet.com/filaments/pom/" }]
        },
        {
          id: "pbt", nameCn: "PBT", nameEn: "Polybutylene Terephthalate", family: "PBT",
          color: "#7fd6ff",
          tg: [40, 55], tm: [220, 225], hdt: [55, 70],
          printTemp: [230, 260], bedTemp: [70, 100],
          tensile: [45, 60], flexural: [80, 90], impact: [3, 6], impactUnit: "kJ/m²", elongation: [50, 200],
          density: [1.30, 1.31], hygroscopic: "低",
          difficulty: 3, warp: "中", enclosure: "建议", drying: "建议 80–100℃/4h（防水解）",
          safetyLevel: 0, fumes: "低挥发（酯类）",
          safetyNote: "PBT 释放物少，安全性尚可；但打印温度偏高，保持通风即可。",
          applications: ["电气件", "耐化学容器", "汽车传感器壳"],
          drawbacks: ["结晶收缩控制难", "市售耗材较少"],
          note: "PBT 与 PET 同族，耐化学性与电绝缘性好，属于小众工程料。",
          sources: [{ name: "All3DP", url: "https://all3dp.com/1/3d-printer-filament-types-3d-printing-3d-filament/" }]
        },
        {
          id: "pps", nameCn: "PPS", nameEn: "Polyphenylene Sulfide", family: "高温PPS",
          color: "#f9685f",
          tg: [85, 95], tm: [280, 285], hdt: [100, 135],
          printTemp: [300, 360], bedTemp: [130, 160],
          tensile: [60, 75], flexural: [95, 120], impact: [2, 6], impactUnit: "kJ/m²", elongation: [2, 10],
          density: [1.34, 1.36], hygroscopic: "低",
          difficulty: 5, warp: "中", enclosure: "必需", drying: "建议 110–150℃/4h",
          safetyLevel: 2, fumes: "高温含硫气体（H₂S/SO₂）",
          safetyNote: "PPS 打印温度 300℃+，释放物浓度高且成分复杂，必须高温封闭腔体+强通风+过滤，腔温常需 100℃+。",
          applications: ["航空航天", "化工耐腐蚀件", "高温电气", "半导体夹具"],
          drawbacks: ["需高温工程机", "需硬化喷嘴", "价格高"],
          note: "PPS 耐化学腐蚀与阻燃性极佳；打印几乎必须 300℃+ 热端与高温腔。未增强料典型值，CF/GF 增强后拉伸可达 100–150 MPa。",
          sources: [{ name: "Bambu Lab Wiki", url: "https://wiki.bambulab.com/en/filament" }]
        },
        {
          id: "ppsu", nameCn: "PPSU", nameEn: "Polyphenylsulfone", family: "高温PSU",
          color: "#f9685f",
          tg: [215, 225], tm: null, hdt: [190, 215],
          printTemp: [330, 390], bedTemp: [130, 160],
          tensile: [65, 75], flexural: [85, 105], impact: [50, 70], impactUnit: "kJ/m²(约算)", elongation: [60, 90],
          density: [1.29, 1.30], hygroscopic: "中",
          difficulty: 5, warp: "低", enclosure: "必需", drying: "建议 135–150℃/4h",
          safetyLevel: 1, fumes: "高温芳香族挥发物",
          safetyNote: "PPSU 无定形、耐热极高，但 340℃+ 打印必须封闭腔体+强通风+过滤。",
          applications: ["医疗灭菌件", "航空件", "高温电气"],
          drawbacks: ["价格极高", "需顶级高温机", "小众"],
          note: "PPSU 无定形、翘曲小，可蒸汽灭菌，用于医疗/食品级高温场景；抗冲击为注塑级 IZOD 值约算（600–700 J/m），打印件通常更低。",
          sources: [{ name: "Bambu Lab Wiki", url: "https://wiki.bambulab.com/en/filament" }]
        },
        {
          id: "peek", nameCn: "PEEK", nameEn: "Polyether Ether Ketone", family: "高温PEEK/PEKK",
          color: "#f9685f",
          tg: [143, 150], tm: [340, 345], hdt: [150, 160],
          printTemp: [360, 430], bedTemp: [120, 160],
          tensile: [90, 100], flexural: [140, 165], impact: [4, 10], impactUnit: "kJ/m²", elongation: [20, 50],
          density: [1.30, 1.32], hygroscopic: "低",
          difficulty: 5, warp: "中", enclosure: "必需", drying: "建议 120–150℃/4–6h",
          safetyLevel: 3, fumes: "高温芳香族挥发物（浓度显著）",
          safetyNote: "PEEK 需 350℃+ 打印与高温腔（腔温 90–160℃），高温释放物与超细颗粒浓度高，必须使用封闭腔体+HEPA/活性炭过滤+强通风，是打印安全要求最高的材料之一。",
          applications: ["医疗植入", "航空航天", "半导体", "高性能机械件"],
          drawbacks: ["价格昂贵（数倍于常规料）", "需专用高温机", "需退火后处理"],
          note: "PEEK 打印需全程高温环境（腔温常需 90–160℃），层间结晶度决定最终强度，通常需退火；HDT 为 1.82MPa 载荷值（0.45MPa 下约 290–315℃）。缺口冲击为注塑级典型值，打印件更低。",
          sources: [{ name: "Prusa 材料库", url: "https://help.prusa3d.com/materials" }]
        },
        {
          id: "pekk", nameCn: "PEKK", nameEn: "Polyetherketoneketone", family: "高温PEEK/PEKK",
          color: "#f9685f",
          tg: [147, 162], tm: [300, 330], hdt: [140, 170],
          printTemp: [340, 390], bedTemp: [120, 150],
          tensile: [85, 100], flexural: [130, 150], impact: [5, 10], impactUnit: "kJ/m²", elongation: [10, 30],
          density: [1.28, 1.30], hygroscopic: "低",
          difficulty: 5, warp: "中", enclosure: "必需", drying: "建议 120℃/4h",
          safetyLevel: 3, fumes: "高温芳香族挥发物",
          safetyNote: "PEKK 与 PEEK 同级安全要求：高温腔+强通风+过滤。",
          applications: ["航空结构件", "碳纤复合", "油气工业"],
          drawbacks: ["价格极高", "需高温机", "小众"],
          note: "PEKK 结晶速率比 PEEK 慢，层间结合控制是难点。",
          sources: [{ name: "Prusa 材料库", url: "https://help.prusa3d.com/materials" }]
        },
        {
          id: "pei", nameCn: "PEI", nameEn: "Polyetherimide (ULTEM)", family: "高温PSU",
          color: "#f9685f",
          tg: [215, 217], tm: null, hdt: [190, 200],
          printTemp: [340, 390], bedTemp: [130, 160],
          tensile: [70, 85], flexural: [130, 145], impact: [4, 8], impactUnit: "kJ/m²", elongation: [25, 60],
          density: [1.27, 1.28], hygroscopic: "中",
          difficulty: 5, warp: "低", enclosure: "必需", drying: "建议 130–150℃/4h",
          safetyLevel: 2, fumes: "高温芳香族挥发物",
          safetyNote: "PEI 释放物浓度高（芳香族），必须封闭腔体+过滤+强通风；吸湿也需严格控制。",
          applications: ["航空航天内饰", "高温电气", "汽车", "医疗"],
          drawbacks: ["价格高", "需高温封闭腔", "吸湿"],
          note: "ULTEM 1010/9085 为通用电气（SABIC）商品名，PEI 是材料通称；1010 伸长率约 60%，9085（航空级）约 6%。",
          sources: [{ name: "Prusa 材料库", url: "https://help.prusa3d.com/materials" }]
        },
        {
          id: "pvdf", nameCn: "PVDF", nameEn: "Polyvinylidene Fluoride", family: "PVDF",
          color: "#7fd6ff",
          tg: [-40, -35], tm: [160, 175], hdt: [55, 90],
          printTemp: [220, 260], bedTemp: [70, 100],
          tensile: [35, 50], flexural: [55, 70], impact: [15, 40], impactUnit: "kJ/m²(约算)", elongation: [50, 300],
          density: [1.75, 1.78], hygroscopic: "低",
          difficulty: 4, warp: "高", enclosure: "建议", drying: "建议 70–80℃/2–4h",
          safetyLevel: 2, fumes: "过温时氟化氢（HF）风险",
          safetyNote: "PVDF 正常打印释放物少；但一旦严重过热（>300℃）可能释放氟化氢，必须控温并保持通风，切勿空烧。",
          applications: ["化工耐腐蚀管路", "压电/传感器件", "户外耐候件"],
          drawbacks: ["过热有HF风险", "价格较高", "小众"],
          note: "PVDF 耐化学腐蚀性极佳，用于化工与压电应用。",
          sources: [{ name: "Polymaker 官方", url: "https://polymaker.com/filaments/" }]
        },
        {
          id: "pc-abs", nameCn: "PC-ABS", nameEn: "Polycarbonate/ABS Blend", family: "PC",
          color: "#f9685f",
          tg: [105, 120], tm: null, hdt: [106, 112],
          printTemp: [250, 270], bedTemp: [90, 105],
          tensile: [40, 50], flexural: [66, 85], impact: [20, 30], impactUnit: "kJ/m²", elongation: [4, 10],
          density: [1.08, 1.12], hygroscopic: "中",
          difficulty: 3, warp: "高", enclosure: "建议", drying: "建议 75℃/6h",
          safetyLevel: 1, fumes: "苯乙烯 + 高温微量双酚A类",
          safetyNote: "PC-ABS 同时含 ABS 的苯乙烯释放与 PC 的高温释放物，务必通风，建议封闭腔体+过滤；综合了 PC 的耐热与 ABS 的韧性。",
          applications: ["汽车内外饰", "电子产品外壳", "耐冲击结构件", "电镀装饰件"],
          drawbacks: ["翘曲收缩大，建议封闭舱", "打印温度高，需全金属热端", "吸湿需干燥，建议退火"],
          note: "Polymaker PC-ABS 官方 TDS V5.4（打印件实测）：拉伸 39.9–42.3 MPa、HDT 106–112℃（载荷 1.8/0.45MPa）、Charpy 缺口冲击 25.8 kJ/m²、Tg 109℃、伸长率 4.2%。",
          sources: [{ name: "Polymaker 官方技术数据一览", url: "https://wiki.polymaker.com/polymaker-wiki/polymaker-wiki-zh/polymaker-chan-pin/polymaker-filaments/technical-data-at-a-glance.md" }]
        },
        {
          id: "pa12-cf", nameCn: "PA12-CF", nameEn: "Carbon Fiber Nylon 12", family: "尼龙PA",
          color: "#f2c94c",
          tg: [45, 60], tm: [170, 180], hdt: [105, 131],
          printTemp: [280, 300], bedTemp: [40, 60],
          tensile: [70, 90], flexural: [92, 115], impact: [8, 12], impactUnit: "kJ/m²", elongation: [4, 8],
          density: [1.03, 1.08], hygroscopic: "高",
          difficulty: 3, warp: "低", enclosure: "否", drying: "必需 100℃/10h",
          safetyLevel: 1, fumes: "内酰胺类 + 碳纤维粉尘",
          safetyNote: "PA12-CF 释放物与尼龙相当（比 PA6 少），高温打印建议通风；碳纤粉尘需防护。",
          applications: ["轻量化结构件", "无人机部件", "工装夹具", "耐磨传动件"],
          drawbacks: ["打印后需退火+调湿才获全强度", "需 280℃+ 热端与硬化喷嘴", "断裂伸长率低、偏脆"],
          note: "Fiberon PA12-CF10 官方 TDS V1.1：拉伸 71.7–77.4 MPa（干态退火样）、HDT 105–131℃（1.8/0.45MPa）、Charpy 缺口冲击 9.9–10.2 kJ/m²、密度 1.06；官方热床仅 40–50℃（低翘曲设计），退火 100℃/16h + 调湿 48h。",
          sources: [{ name: "Polymaker 官方技术数据一览", url: "https://wiki.polymaker.com/polymaker-wiki/polymaker-wiki-zh/polymaker-chan-pin/polymaker-filaments/technical-data-at-a-glance.md" }]
        },
        {
          id: "pet-cf", nameCn: "PET-CF", nameEn: "Carbon Fiber PET", family: "PET系",
          color: "#22c3a6",
          tg: [75, 85], tm: [240, 260], hdt: [105, 150],
          printTemp: [270, 300], bedTemp: [70, 80],
          tensile: [60, 80], flexural: [105, 140], impact: [4, 8], impactUnit: "kJ/m²", elongation: [2, 6],
          density: [1.30, 1.35], hygroscopic: "中",
          difficulty: 3, warp: "低", enclosure: "否", drying: "必需 100℃/10h",
          safetyLevel: 1, fumes: "低挥发 + 碳纤维粉尘",
          safetyNote: "PET-CF 释放物少，建议通风；碳纤粉尘需防护。性能高度依赖退火（120℃/10h）。",
          applications: ["高刚度结构件", "耐化学件", "工装夹具", "耐热外壳"],
          drawbacks: ["需硬化喷嘴", "脆性大（伸长率仅 2.4%）", "退火才能获得高 HDT"],
          note: "Fiberon PET-CF17 官方 TDS V1.0（退火样 120℃/10h）：拉伸 65.9 MPa、HDT 105–147.5℃（1.8/0.45MPa）、Charpy 缺口冲击 5.1 kJ/m²、密度 1.34；拓竹 PET-CF 未退火 HDT 约 87℃。",
          sources: [{ name: "Polymaker 官方技术数据一览", url: "https://wiki.polymaker.com/polymaker-wiki/polymaker-wiki-zh/polymaker-chan-pin/polymaker-filaments/technical-data-at-a-glance.md" }]
        },
        {
          id: "pps-cf", nameCn: "PPS-CF", nameEn: "Carbon Fiber PPS", family: "高温PPS",
          color: "#f9685f",
          tg: [90, 100], tm: [279, 285], hdt: [133, 255],
          printTemp: [310, 350], bedTemp: [80, 90],
          tensile: [55, 75], flexural: [94, 120], impact: [4, 8], impactUnit: "kJ/m²", elongation: [1, 4],
          density: [1.25, 1.30], hygroscopic: "低",
          difficulty: 5, warp: "低", enclosure: "否", drying: "建议 100℃/10h",
          safetyLevel: 2, fumes: "高温含硫气体（H₂S/SO₂）+ 碳纤维粉尘",
          safetyNote: "PPS-CF 需 310–350℃ 打印，释放含硫气体与 VOC，强烈建议通风+高效过滤（UL94 V0 阻燃）；碳纤粉尘需防护。",
          applications: ["航空航天", "化工耐腐蚀结构件", "半导体夹具", "高温电气"],
          drawbacks: ["需 310℃+ 高温热端", "线材在盘上脆、易断", "打印后必须退火 125℃/16h"],
          note: "Fiberon PPS-CF10 官方 TDS V1.1：拉伸 59.4 MPa、HDT 133–252.5℃（1.8/0.45MPa 载荷）、Charpy 缺口冲击 5.3 kJ/m²、密度 1.29、Tg 97.7℃；官方无需加热舱（拓竹 PPS-CF 则要求封闭腔体）。",
          sources: [{ name: "Polymaker 官方技术数据一览", url: "https://wiki.polymaker.com/polymaker-wiki/polymaker-wiki-zh/polymaker-chan-pin/polymaker-filaments/technical-data-at-a-glance.md" }]
        },
        {
          id: "ppa-cf", nameCn: "PPA-CF", nameEn: "Carbon Fiber PPA (Polyphthalamide)", family: "PPA",
          color: "#f9685f",
          tg: [120, 130], tm: [255, 265], hdt: [150, 227],
          printTemp: [280, 310], bedTemp: [100, 120],
          tensile: [120, 170], flexural: [200, 210], impact: [10, 42], impactUnit: "kJ/m²", elongation: [2, 6],
          density: [1.25, 1.30], hygroscopic: "高",
          difficulty: 4, warp: "低", enclosure: "必需", drying: "必需 100–140℃/8–12h",
          safetyLevel: 1, fumes: "酰胺类 VOC + 碳纤维粉尘",
          safetyNote: "PPA-CF 打印温度高（280–310℃），官方要求通风良好或装过滤/排气；打印环境湿度须 <20%RH；碳纤粉尘需防护。",
          applications: ["汽车结构件", "无人机/机械臂", "工业精密件", "金属替代件"],
          drawbacks: ["必须封闭腔体打印机", "极吸湿，需严格干燥", "需硬化喷嘴与胶水辅助附着"],
          note: "拓竹官方（wiki + TDS 镜像交叉）：拉伸 168±4 MPa、弯曲 208±6 MPa、HDT 227℃（0.45MPa）、冲击 41.7 kJ/m²（官方未注明缺口方式）、Tm 258℃、密度 1.25；吸湿率比普通 PA6-CF 低 66%。",
          sources: [{ name: "Bambu Lab Wiki", url: "https://wiki.bambulab.com/zh/filament/ppacf" }]
        },
        {
          id: "peba", nameCn: "PEBA", nameEn: "Polyether Block Amide", family: "柔性",
          color: "#c98bf9",
          tg: null, tm: null, hdt: null,
          printTemp: [230, 260], bedTemp: [40, 90],
          tensile: [16, 35], flexural: null, impact: [40, 70], impactUnit: "kJ/m²(不断裂)", elongation: [400, 900],
          density: [1.00, 1.05], hygroscopic: "高",
          difficulty: 3, warp: "低", enclosure: "否", drying: "建议 60℃/8h 或 70℃/5h",
          safetyLevel: 0, fumes: "低气味低 VOC",
          safetyNote: "PEBA（聚醚嵌段酰胺）为高性能弹性体，释放物少；建议使用全新热端（勿用打印过碳纤料的热端）。",
          applications: ["运动鞋中底", "可穿戴设备", "减震结构", "医疗康复辅具"],
          drawbacks: ["价格昂贵", "柔性材料打印窗口窄", "吸湿需干燥"],
          note: "eSUN PEBA-85A 官方：密度 1.05、回弹率最高 70%、使用温度 -40~90℃；喷嘴温度官方未公开，取同系 PEBA-90A 官方值（230–260℃）与 Siraya Rebound PEBA-85A 交叉。",
          sources: [{ name: "eSUN 官方", url: "https://www.esun3d.com/flexibility-elasticity/" }]
        },
        {
          id: "asa-cf", nameCn: "ASA-CF", nameEn: "Carbon Fiber ASA", family: "ABS/ASA",
          color: "#f9a54f",
          tg: [100, 108], tm: null, hdt: [100, 110],
          printTemp: [240, 270], bedTemp: [100, 110],
          tensile: [40, 55], flexural: [80, 105], impact: [5, 8], impactUnit: "kJ/m²", elongation: [2, 6],
          density: [1.07, 1.15], hygroscopic: "低",
          difficulty: 4, warp: "中", enclosure: "建议", drying: "建议 80℃/4h",
          safetyLevel: 1, fumes: "苯乙烯类 + 碳纤维粉尘",
          safetyNote: "ASA-CF 兼具 ASA 的苯乙烯释放与碳纤粉尘问题，需通风；刚性显著提升、韧性下降。",
          applications: ["户外结构件", "无人机外壳", "汽车外饰加强件"],
          drawbacks: ["磨喷嘴", "韧性低于纯 ASA", "价格较高"],
          note: "官方打印件实测（Polymaker Fiberon ASA-CF08）：拉伸 43.5 MPa、HDT 103℃、缺口冲击 5.5 kJ/m²、密度 1.09。",
          sources: [{ name: "Polymaker 官方技术数据一览", url: "https://wiki.polymaker.com/polymaker-wiki/polymaker-wiki-zh/polymaker-chan-pin/polymaker-filaments/technical-data-at-a-glance.md" }]
        },
        {
          id: "pctg", nameCn: "PCTG", nameEn: "Glycol-modified PCT (透明耐化聚酯)", family: "PET系",
          color: "#22c3a6",
          tg: [78, 84], tm: null, hdt: [74, 76],
          printTemp: [250, 270], bedTemp: [75, 90],
          tensile: [43, 50], flexural: [70, 80], impact: [8, 20], impactUnit: "kJ/m²", elongation: [100, 340],
          density: [1.23, 1.29], hygroscopic: "低",
          difficulty: 2, warp: "低", enclosure: "否", drying: "低吸湿；受潮后建议 65℃/4–6h",
          safetyLevel: 0, fumes: "低气味；高温微量乙醛/乙酸类蒸气",
          safetyNote: "PCTG 打印气味极低，释放物少（正常通风即可）；耐化学性与透明性优于 PETG，适合化工接触场景。",
          applications: ["透明/半透明件", "耐化学容器", "医疗及食品接触件（部分品牌标称）", "灯罩/光学展示件"],
          drawbacks: ["易拉丝，需仔细调回抽", "附着力强易粘板，需脱模剂", "价格高于 PETG"],
          note: "多源交叉（3DXTech 博客/3D-Fuel Pro PCTG TDS/Prusa 材料表）：Tg 78–84℃、HDT 74–76℃（0.455MPa）、断裂伸长 220–340%（3D-Fuel 官方，远超 PETG）、冲击 Izod 860J/m≈93 kJ/m² vs Charpy 8 kJ/m²（口径差异大）；Polymaker 目前无 PCTG 产品。",
          sources: [{ name: "3DXTech MAX-G PCTG 官方", url: "https://www.3dxtech.com/products/max-g-pctg" }]
        },
        {
          id: "pa-gf", nameCn: "PA-GF", nameEn: "Glass Fiber Reinforced Nylon", family: "尼龙PA",
          color: "#f2c94c",
          tg: [55, 71], tm: [214, 225], hdt: [157, 191],
          printTemp: [270, 300], bedTemp: [40, 100],
          tensile: [78, 90], flexural: [130, 140], impact: [10, 20], impactUnit: "kJ/m²", elongation: [2, 4],
          density: [1.20, 1.22], hygroscopic: "极高",
          difficulty: 3, warp: "低", enclosure: "否", drying: "必需 100℃/10h，储存湿度 <20%",
          safetyLevel: 1, fumes: "酰胺类（己内酰胺）+ 玻纤粉尘",
          safetyNote: "PA-GF 释放己内酰胺蒸气需通风；玻纤粉尘吸入有害（打磨需口罩+护目镜）；玻纤严重磨损喷嘴（黄铜约 9h 寿命，须硬化钢/红宝石）。",
          applications: ["汽车与工程结构件", "工业夹具/工装", "齿轮/轴承座", "高强度耐热外壳"],
          drawbacks: ["吸湿极快，必须烘干+退火(100℃/16h)", "玻纤磨喷嘴", "湿态性能大幅下降"],
          note: "以 Polymaker Fiberon PA6-GF25 官方 TDS V1.1 为准（打印件 XY 向，退火+调湿样）：拉伸 80.1 MPa、HDT 191℃（0.45MPa）/157℃（1.8MPa）、缺口 Charpy 10 kJ/m²、弯曲 133.8 MPa、伸长 2.4%、Tg 70.4℃（DSC）、Tm 214.5℃；Polymaker 独特 Warp-Free 工艺床温 40–50℃（无加热腔），其他品牌（BASF Ultrafuse PA6 GF30）床温 100℃ 并建议腔体。",
          sources: [{ name: "Polymaker 官方技术数据一览", url: "https://wiki.polymaker.com/polymaker-wiki/polymaker-wiki-zh/polymaker-chan-pin/polymaker-filaments/technical-data-at-a-glance.md" }]
        },
        {
          id: "peek-cf", nameCn: "PEEK-CF", nameEn: "Carbon Fiber PEEK", family: "高温PEEK/PEKK",
          color: "#f9685f",
          tg: [143, 150], tm: [343, 345], hdt: [200, 265],
          printTemp: [360, 450], bedTemp: [120, 160],
          tensile: [105, 130], flexural: [130, 150], impact: [7, 15], impactUnit: "kJ/m²", elongation: [3, 4],
          density: [1.36, 1.40], hygroscopic: "低",
          difficulty: 5, warp: "高", enclosure: "必需", drying: "建议 120℃/4h",
          safetyLevel: 3, fumes: "高温芳香族挥发物（苯酚类/CO）+ 碳纤维粉尘",
          safetyNote: "PEEK-CF 400℃ 级加工：必须高温封闭腔体（70–150℃）+ 强通风 + HEPA/活性炭过滤；碳纤粉尘需防护；打印速度仅 15–30 mm/s。",
          applications: ["航空航天/军工结构件", "油气/半导体设备件", "医疗高温灭菌器械", "高温替代金属件"],
          drawbacks: ["需工业级设备（360–450℃ 热端+主动加热腔）", "成本极高", "半结晶收缩大，易翘曲"],
          note: "3DXTech CarbonX PEEK-CF10 官方 TDS Rev3.0（10% 碳纤，样件 400℃/140℃ 打印）：拉伸 105 MPa、弯曲 136 MPa、HDT 265℃（0.45MPa）、伸长 3%、Tg 143℃、密度 1.39；官方热端 360–450℃、床 120–160℃、腔 70–150℃；Luvocom 交叉：拉伸 126 MPa、缺口 Charpy 7 kJ/m²。",
          sources: [{ name: "3DXTech CarbonX 系列官方", url: "https://www.3dxtech.com/collections/carbonx" }]
        },
        {
          id: "peek-gf", nameCn: "PEEK-GF", nameEn: "Glass Fiber PEEK（GF20）", family: "高温PEEK/PEKK",
          color: "#f9685f",
          tg: [143, 150], tm: [343, 345], hdt: [200, 300],
          printTemp: [360, 450], bedTemp: [120, 160],
          tensile: [100, 120], flexural: [130, 150], impact: null, impactUnit: "kJ/m²", elongation: [2, 4],
          density: [1.40, 1.46], hygroscopic: "低",
          difficulty: 5, warp: "高", enclosure: "必需", drying: "建议 120℃/4h",
          safetyLevel: 3, fumes: "高温芳香族挥发物（苯酚类/CO）+ 玻纤粉尘",
          safetyNote: "PEEK-GF 与 PEEK-CF 同级安全要求：高温封闭腔体+强通风+过滤；玻纤流动性差更易堵头、磨损更重。",
          applications: ["密封件/齿轮/推力垫圈", "泵与压缩机部件", "油气/化工耐蚀高温件", "航空航天结构件"],
          drawbacks: ["需工业级设备", "玻纤易堵头、磨喷嘴", "结晶控制难"],
          note: "口径说明：3DXTech 官方玻纤增强 PEEK 型号为 FIBREX PEEK+GF20（20% 玻纤，无 GF10）。官方 TDS Rev1.0：拉伸 105 MPa、弯曲 130 MPa、HDT 300℃（0.45MPa）、伸长 2.5%、Tg 143℃、Tm 343℃、密度 1.44、连续使用温度 260℃；热端 360–450℃/床 120–160℃/腔 70–150℃；冲击数据官方未发布。",
          sources: [{ name: "3DXTech CarbonX 系列官方", url: "https://www.3dxtech.com/collections/carbonx" }]
        }
      ]
    }
  ],

  brands: [
    {
      id: "bambulab", nameCn: "拓竹", nameEn: "Bambu Lab", icon: "🐼",
      hq: "中国深圳", url: "https://bambulab.com/zh-cn",
      flagship: "PLA Tough（高韧性）、PLA-CF、PETG HF（高速）、PA6-CF、PAHT-CF、PPA-CF、PPS-CF、PLA Pure（食品级）等；与自家 X 系列/H2D 机型及 AMS 系统深度联动",
      reputation: "消费级高端品牌，材料与硬件一体化生态（RFID 料盒自动识别参数），色彩丰富、型号从入门 PLA 到 PPS 级高温工程料全覆盖，品控稳定、官方参数完善",
      materials: ["PLA Basic", "PLA Matte", "PLA Silk/Silk+", "PLA Tough/Tough+", "PLA Translucent", "PLA Lite", "PLA Metal", "PLA Aero", "PLA Dynamic", "PLA Galaxy", "PLA Glow", "PLA Wood", "PLA Marble", "PLA Sparkle", "PLA Pure（食品级）", "PLA-CF", "PETG Basic", "PETG Translucent", "PETG Matte", "PETG HF", "PETG-CF", "ABS", "ABS-GF", "ASA", "ASA Aero", "ASA-CF", "PC", "PC FR", "TPU 95A HF", "TPU for AMS", "TPU 85A/90A", "PA6-CF", "PA6-GF", "PAHT-CF", "PPA-CF", "PET-CF", "PPS-CF", "PVA", "易剥离支撑系列"],
      sourceUrls: ["https://wiki.bambulab.com/zh/general/filament-guide-material-table", "https://bambulab.com/zh-cn"]
    },
    {
      id: "kexcelled", nameCn: "Kexcelled（诺思贝瑞）", nameEn: "KEXCELLED", icon: "🔷",
      hq: "中国苏州（诺思贝瑞新材料科技）", url: "https://kexcelled3d.com",
      flagship: "超高温工程料 THE K11/K12 系列：PEEK、PEEK CF10/GF10、PEKK、PPSU、PEI 1010/9085；工程主力 K8 PA-CF、K9 PPA-CF15、K10 PPS-CF10",
      reputation: "以工程料与超高温料（PEEK/PEKK/PEI/PPSU）见长的专业高分子企业，产品线在国产耗材中较全、性价比高，主要面向海外市场",
      materials: ["K3/K5 PLA", "K5 PLA Pro(PLA+)", "K5 PLA M（哑光）", "K5 PLA Silk/Magic/Sparkle/Streams/渐变/变色/金属", "K5/K6 PLA CF", "K5 PLA Wood/Coffee", "K6 PLA FG（食品级）/FR（阻燃）", "K5/K6 PETG", "PETG Rapid", "PETG M/CF/GF/T", "K5/K6 ABS", "ABS Pro/Rapid/M/T/CC/P", "K6 ABS FR", "K3/K5 ASA", "K8 TPU 95A~60A/64D/77D", "TPU 90A Matte", "TPU AIR（发泡）", "OBC 弹性体", "K8/K10 PC", "K9 PC FR", "K8 PA-CF", "K9 PPA-CF15", "K9 PEBA", "K7 PET-CF10", "K10 PPS-CF10", "K11 PEEK/PEEK Pro/PEEK-CF10/PEEK-GF10", "K11 PEKK", "K11 PPSU", "K11 PEI 1010/9085", "K12 PEEK Ultra", "K6 PVA/BVOH/HIPS/BAS70/UCM300 支撑"],
      sourceUrls: ["https://kexcelled3d.com", "https://kexcelled3d.com/pages/about-us"]
    },
    {
      id: "sunlu", nameCn: "三绿", nameEn: "SUNLU", icon: "☀️",
      hq: "中国珠海（三绿实业）", url: "https://www.sunlu.com",
      flagship: "快打（High Speed）高速系列、PLA Meta（低收缩高韧性）、PLA+ 2.0、PA6-CF/PA12-CF 尼龙碳纤、在售 PEEK 高温料",
      reputation: "全球出货量领先的性价比品牌，品类覆盖广（PLA 到 PEEK）、色彩丰富，干燥箱等配件生态完善，价格亲民",
      materials: ["PLA", "PLA Classic/Lite", "PLA+", "PLA+ 2.0", "PLA Meta", "PLA Matte", "PLA Silk（多色/彩虹）", "PLA 透明/银河/闪光/夜光/金属/木质/大理石", "PLA-CF", "LW-PLA", "APLA（不拉丝）", "快打系列（高速 PLA/PETG/ABS）", "PETG", "PETG 2.0", "PETG 透明/夜光", "PETG-CF", "ABS", "ABS 透明", "ABS-FR", "ABS-GF", "ASA", "PC-ABS", "Easy PA", "PA6-CF", "PA6-GF", "PA12-CF", "TPU 95A/90A", "Silk TPU", "PP", "PP 2.0", "PCL", "PVB", "PEEK", "PVA"],
      sourceUrls: ["https://www.sunlu.com/zh-cn/collections/all"]
    },
    {
      id: "polymaker", nameCn: "Polymaker", nameEn: "Polymaker（上海聚复材料）", icon: "🔺",
      hq: "中国上海", url: "https://polymaker.com",
      flagship: "PolyMax 系列（PC/PA 增韧）、Fiberon 碳纤/玻纤增强工程料（PA6-CF20、PA12-CF10、PET-CF17、PPS-CF10）、PolySonic 高速料、PolySmooth（PVB 抛光）、PolyDissolve S1 水溶支撑",
      reputation: "全球化高端品牌，工程料口碑好、强度数据扎实，品控稳定、包装环保，社区生态兼容好（2024 年起 PolyLite 系列更名 PolyMaker 系列）",
      materials: ["PolyMaker PLA", "PLA Pro", "PolyMax PLA", "LW-PLA", "PLA-CF", "Matte PLA", "Draft PLA", "PolySonic PLA/PETG", "HT-PLA/HT-PLA-GF/HT-PLA Pro", "PolyMaker PETG", "PolyMax PETG", "PolyMaker ABS Pro/Max", "PolyMaker ASA", "PolyFlex TPU90/95/95-HF", "PolyLite PC", "PolyMax PC", "PC-ABS", "PolyMide CoPA", "Panchroma 彩色 PLA 系列", "CoSPLA", "Fiberon PA6-CF20/GF25", "Fiberon PA612-CF15", "Fiberon PA12-CF10", "Fiberon PET-CF17/GF15", "Fiberon PPS-CF10/GF20", "Fiberon ASA-CF08", "Fiberon PETG-rCF08", "Fiberon ESD 系列", "PolySmooth/PolyCast PVB", "PolyDissolve S1", "PolySupport"],
      sourceUrls: ["https://wiki.polymaker.com/polymaker-products/polymaker-filaments", "https://polymaker.com/filaments/"]
    },
    {
      id: "esun", nameCn: "eSUN", nameEn: "eSUN（易生/光华伟业）", icon: "🔋",
      hq: "中国深圳（光华伟业）", url: "https://www.esun3d.com",
      flagship: "ePLA-ST（高韧性）、ePLA-CF、ePA-CF、ePAHT-CF（高温尼龙碳纤）、ePETG-CF、PET-CF、ePC；工程料矩阵（PA/PC/ESD/阻燃）齐全",
      reputation: "老牌国产耗材大厂，型号命名规范（e 前缀）、品类最全，从通用料到工程料/柔性料全覆盖，TDS 文档公开透明、性价比高",
      materials: ["ePLA", "ePLA-Basic/Lite", "ePLA-Pro(PLA+)", "ePLA-HS（高速）", "ePLA-Matte", "ePLA-Silk 系列", "PLA-Clear", "ePLA-Metal", "ePLA-Luminous", "PLA-Coffee", "ePLA-CF", "ePLA-ST", "ePLA-LW", "ePETG", "ePETG-Pro", "ePETG-CF", "PETG-Matte", "eABS", "eABS-HS/HT/Max", "eABS-CF/GF", "eASA", "ePA", "ePA-CF", "ePA12", "ePA12-CF", "ePAHT-CF", "PET-CF", "ePC", "PC-ESD", "PET-FR", "ABS-ESD", "eTPU-95A", "eFlex-TPU-87A", "Elastic-TPE-83A", "eTPU-64D", "eTPU-LW", "PEBA 系列", "HIPS", "PVA", "PLA-Cast"],
      sourceUrls: ["https://www.esun3d.com/filaments/", "https://www.esun3d.com/engineering-materials/"]
    },
    {
      id: "prusament", nameCn: "Prusament", nameEn: "Prusament（Prusa 官方）", icon: "🔤",
      hq: "捷克布拉格（Prusa Research）", url: "https://prusament.com",
      flagship: "PC Blend（PC 共混工程料）、PC Space Grade（航天级 PC）、PA11-CF 碳纤尼龙、PEI 1010",
      reputation: "官方自产、逐卷附质检报告，品控与直径公差极严，色彩丰富，被视为消费级耗材标杆；价格偏高",
      materials: ["PLA", "rPLA（再生）", "PETG", "PETG-CF", "PETG V0", "PETG Recycled", "PETG Ultraglow", "PETG Magnetite 40", "PETG Tungsten 75", "ASA", "PC Blend", "PC Blend-CF", "PC Space Grade", "PVB", "PP", "PP-GF", "PA11-CF", "PEI 1010", "TPU 95A", "Woodfill（木质）"],
      sourceUrls: ["https://prusament.com/materials/", "https://prusament.com/materials/prusament-pc-blend/"]
    },
    {
      id: "creality", nameCn: "创想三维", nameEn: "Creality", icon: "🖨️",
      hq: "中国深圳", url: "https://www.creality.com",
      flagship: "Hyper PLA 高速系列（与 K1/K2 高速机深度适配）、Hyper PLA-CF/PETG-CF、HP ASA/TPU",
      reputation: "国产整机巨头自产耗材，Hyper 系列主打高速打印、性价比高；CR 系列入门实惠",
      materials: ["CR-PLA", "CR-PLA Carbon", "CR-PETG", "CR-ABS", "CR-Silk", "CR-Wood", "Hyper PLA", "Hyper PLA-CF", "Hyper PLA RFID", "Hyper Lightweight PLA", "Hyper Luminous PLA", "Hyper Rainbow PLA", "Hyper PETG", "Hyper PETG-CF", "Hyper ABS", "Hyper PC", "HP ASA", "HP TPU"],
      sourceUrls: ["https://store.creality.com", "https://www.creality.com"]
    },
    {
      id: "anycubic", nameCn: "纵维立方", nameEn: "Anycubic", icon: "🟢",
      hq: "中国深圳", url: "https://www.anycubic.com",
      flagship: "PLA+（高韧性主力）、高速 PLA、PET-CF、PA6-CF 碳纤工程线（与 Kobra 系列生态绑定）",
      reputation: "性价比高，与 Kobra 系列打印机组成完整配套生态，近年扩展碳纤/工程料线，品控中上",
      materials: ["PLA", "PLA+", "PLA Basic", "PLA Silk（含双色/三色）", "Matte PLA", "High-Speed PLA", "PLA-CF", "PLA Galaxy/Glow/Marble/Metal", "PETG", "PETG-CF", "PET-CF", "ABS", "ASA", "PC", "PA6-CF", "TPU 95A", "TPU 68D"],
      sourceUrls: ["https://store.anycubic.com/collections/filaments", "https://www.anycubic.com/zh"]
    },
    {
      id: "overture", nameCn: "Overture", nameEn: "Overture", icon: "🔵",
      hq: "美国休斯顿（德克萨斯州）", url: "https://overture3d.com",
      flagship: "Super PLA（高速）、Easy Nylon（易打尼龙）、PC Professional；PLA/PETG 为走量主力",
      reputation: "美系性价比路线，绕线规整、直径公差小（±0.02/0.03mm），品控口碑稳定",
      materials: ["PLA", "PLA Plus", "PLA Professional", "Super PLA", "Matte PLA", "Silk PLA", "Rock/Shimmer/Glow PLA", "渐变 PLA", "Easy PLA", "PETG", "High Speed PETG", "ABS", "ASA", "TPU 95A", "High Speed TPU", "Matte TPU", "Easy Nylon", "PC Professional"],
      sourceUrls: ["https://overture3d.com/collections/filament", "https://overture3d.com/pages/about-us"]
    },
    {
      id: "3dxtech", nameCn: "3DXTech", nameEn: "3DXTech（美国工程料厂）", icon: "⚙️",
      hq: "美国密歇根州大急流城", url: "https://www.3dxtech.com",
      flagship: "ThermaX PEEK/PEKK/PEI 1010/9085 高温工程料、CarbonX PA6-CF/PA12-CF 碳纤尼龙、FluorX PVDF",
      reputation: "美国高性能/工程料专业厂，主打 PEEK/PEI/碳纤及特种料，航空航天与医疗行业背书，1.75/2.85mm 规格齐全；价格高、面向专业用户",
      materials: ["ThermaX PEEK", "ThermaX PEKK-A", "ThermaX PEI 1010/9085", "ThermaX PPS", "ThermaX PPSU", "ThermaX PSU/PES", "ThermaX PPE/PS", "ThermaX HTS1/HTS2/MTS1", "CarbonX PA6-CF", "CarbonX PA12-CF", "CarbonX HTN-CF", "CarbonX PC-CF", "CarbonX PETG-CF", "CarbonX ABS-CF", "CarbonX ASA-CF", "CarbonX PLA-CF", "CarbonX PP-CF", "CarbonX PEEK-CF10", "CarbonX PEKK-A CF15", "CarbonX PEI-CF15", "CarbonX Obsidian Nylon 6-CF", "FluorX PVDF", "3DXLabs PVDF-GF", "3DXSTAT ESD 系列", "常规 ABS/ASA/PLA/PETG/TPU/PC/HIPS"],
      sourceUrls: ["https://www.3dxtech.com/collections", "https://www.3dxtech.com/search?q=carbonx"]
    },
    {
      id: "elegoo", nameCn: "爱乐酷", nameEn: "ELEGOO（深圳智能派科技）", icon: "🐙",
      hq: "中国深圳", url: "https://us.elegoo.com/pages/elegoo-filaments",
      flagship: "Rapid PLA Plus（高速）、Rapid PETG、PAHT-CF、PC-FR（阻燃 PC）；打印机+耗材全生态（海王星系列）",
      reputation: "全球消费级 3D 打印头部品牌（年营收 16 亿+），耗材线与自家海王星系列深度适配，性价比与品控均衡",
      materials: ["PLA", "PLA Basic", "PLA Plus", "PLA Pro", "Rapid PLA Plus", "PLA Matte", "PLA Silk", "PLA Glow", "PLA Wood", "PLA Marble", "PLA Galaxy", "PLA Sparkle", "PLA Metallic", "PLA-CF", "PETG", "PETG Pro", "PETG Translucent", "Rapid PETG", "PETG-CF", "PETG-GF", "ABS", "ASA", "TPU 95A", "Rapid TPU 95A", "PAHT-CF", "PC", "PC-FR", "SLA 光敏树脂系列"],
      sourceUrls: ["https://us.elegoo.com/pages/elegoo-filaments", "https://www.elegoo.com"]
    },
    {
      id: "jayo", nameCn: "Jayo（捷优）", nameEn: "JAYO", icon: "🎁",
      hq: "中国香港（注册地，海外电商主导）", url: "https://jayo3d.com",
      flagship: "PLA Meta、PLA+ 多卷装（5/10 卷经济包）、5KG 大卷装系列",
      reputation: "独立品牌（与创想三维无官方隶属确认），主打大卷装/多卷装经济路线，海外电商销量大，PLA 家族覆盖全",
      materials: ["PLA", "PLA+", "PLA Matte", "PLA Meta", "PLA Silk", "PLA Rainbow", "PLA Galaxy", "PLA Wood", "PETG", "PETG HF", "ABS", "5KG 大卷装系列", "10 卷装经济包", "SLA 光敏树脂"],
      sourceUrls: ["https://jayo3d.com/collections/all"]
    },
    {
      id: "fusrock", nameCn: "FusRock", nameEn: "FusRock（苏州复丝络科新材料）", icon: "🪨",
      hq: "中国苏州", url: "https://www.fusrock.com",
      flagship: "Nex 工程料：NexPA-CF25、PAHT-CF/GF、PPA-CF、ABS-CF、PETG-CF HF、PEBA-95A",
      reputation: "国产工程料新锐品牌，碳纤/玻纤增强与高温尼龙系列齐全，TDS 文档公开",
      materials: ["NexPA-CF25", "NexPA-GF25", "NexABS-CF20", "NexABS-GF25", "NexPET-GF", "PAHT-CF", "PAHT-GF", "PPA-CF", "ABS-CF", "PETG-CF HF", "低气味 ABS", "PC/ABS", "PEBA-95A", "PLA 系列", "PETG 系列", "TPU 系列"],
      sourceUrls: ["https://www.fusrock.com", "https://wiki.fusrock.com/zh/about/about-us"]
    },
    {
      id: "r3d", nameCn: "R3D", nameEn: "R3D（芜湖爱3迪科技）", icon: "🔩",
      hq: "中国芜湖", url: "https://r3dprinter.com",
      flagship: "PLA 全系（丝绸/哑光/彩虹/热变色/夜光）、Rapid PLA、高速 PLA Pro、高速碳纤 PETG",
      reputation: "2014 年成立的专业线材厂，12 条产线日产耗材 8000+kg，出口与电商并行，色彩与高速料齐全",
      materials: ["PLA 全系（丝绸/哑光/彩虹/热变色/夜光）", "Rapid PLA", "PLA+", "高速 PLA Pro", "eSilk Magic/Mystic（幻彩丝绸）", "PETG", "高速碳纤 PETG", "ABS", "TPU", "PA6（尼龙）"],
      sourceUrls: ["https://r3dprinter.com", "https://r3d.en.alibaba.com/zh_CN/company_profile.html"]
    },
    {
      id: "ailizi", nameCn: "爱丽滋", nameEn: "ALIZ（无锡爱丽兹三维科技）", icon: "💠",
      hq: "中国无锡（母公司：江阴龙山合成材料）", url: "http://www.longshanplas.com/ALIZ/",
      flagship: "PLA+ Pro、PETG/PETG-HF、哑光系列；背靠 25 年改性材料经验的母公司（专精特新小巨人+CNAS 实验室）",
      reputation: "2022 年独立品牌，母公司江阴龙山合成材料改性经验 25 年+，工业级工程料与民用耗材并重",
      materials: ["PLA+ Pro", "PLA（高速高韧性）", "PLA Silk", "PETG", "PETG HF", "哑光系列", "ABS", "TPU", "工业级工程料"],
      sourceUrls: ["https://www.longshanplas.com", "https://online.tctasia.cn/zh-cn/showroom-2026/institutions/681bnf"]
    },
    {
      id: "caiduowu", nameCn: "彩多屋", nameEn: "CAILAB（惠州彩多屋科技）", icon: "🎨",
      hq: "中国惠州（仲恺）", url: "https://online.tctasia.cn/zh-cn/showroom-2026/institutions/23bdhh",
      flagship: "PLA+ Bio 系列、丝绸 PIA 系列",
      reputation: "以色彩丰富的 PLA 系列见长，把 3D 打印材料做成'生活方式'的品牌（无独立官网，天猫/淘宝旗舰店运营）",
      materials: ["PLA+ Bio", "丝绸 PIA", "PLA 系列", "PETG", "TPU"],
      sourceUrls: ["https://online.tctasia.cn/zh-cn/showroom-2026/institutions/23bdhh", "https://world.taobao.com/dianpu/415090305_1.htm"]
    },
    {
      id: "qipang", nameCn: "启庞", nameEn: "Kingroon（深圳启庞科技）", icon: "🖥️",
      hq: "中国深圳", url: "https://cn.kingroon.com",
      flagship: "KP3S 系列打印机配套耗材；PLA+/PETG 碳纤线，入门性价比路线",
      reputation: "以高性价比 FDM 打印机（KP3S 等）闻名，耗材为配套生态，入门玩家友好",
      materials: ["PLA+", "PLA Basic", "PETG", "哑光系列", "彩虹系列", "丝绸双色/三色", "PLA-CF", "PETG-CF", "ABS", "TPU"],
      sourceUrls: ["https://cn.kingroon.com", "https://www.kingroon.com"]
    },
    {
      id: "aipuchuang", nameCn: "艾普创", nameEn: "Aipuchuang（艾普创聚合物材料·苏州）", icon: "🧬",
      hq: "中国苏州", url: "https://s.taobao.com/search?q=%E8%89%BE%E6%99%AE%E5%88%9B3D%E6%89%93%E5%8D%B0%E6%9D%90%E6%96%99",
      flagship: "TPU 95A HS（300mm/s 高速耐磨）、PLA-CF（10 款中国传统色）、PPA/PPA-CF/PPA-GF、PC-CF/PC-GF、PA6-CF/PA6-GF、阻燃 PC、食品级 PLA；官方渠道为淘宝直营店 + 抖音商城（公众号：艾普创IPCON）",
      reputation: "2025 年起密集发布新品的苏州新锐线材厂：TPU 95A HS 实测 300mm/s、PPA-CF 弯曲强度破 250MPa、PA6-CF/GF 热变形温度 191–197℃ 且无需腔体加热，走「工业性能 + 国潮配色」差异化路线",
      materials: ["TPU 95A HS", "PLA", "PLA-CF", "PLA（食品级）", "PC", "PC-CF", "PC-GF", "PA6", "PA6-CF", "PA6-GF", "PPA", "PPA-CF", "PPA-GF", "阻燃 PC"],
      sourceUrls: ["https://nanjixiong.com", "https://www.sohu.com", "https://m.163.com"]
    },
    {
      id: "mochuang", nameCn: "魔创", nameEn: "Mochuang（河南魔创科技）", icon: "🎨",
      hq: "中国河南", url: "https://s.1688.com/selloffer/offer_search.htm?keywords=mo-chuang-3d",
      flagship: "哑光 PLA / 哑光 PETG（高纯度、厂家直销），1688 批量直供，价格优势明显",
      reputation: "河南魔创科技旗下耗材品牌，主打哑光质感的 PLA/PETG，通过 1688 平台批量直供（2026-05 行业文章提及与彩多屋同属低价区间），面向农场与批量采购用户",
      materials: ["PLA", "哑光 PLA", "PETG", "哑光 PETG"],
      sourceUrls: ["https://wiki.1688.com/zh/3d-printing-filament/WKfmd1tlr20mio"]
    },
    {
      id: "xibo", nameCn: "犀博", nameEn: "Xibo", icon: "🌈",
      hq: "中国（平台：拼多多）", url: "https://mobile.yangkeduo.com/search_result.html?search_key=%E7%8A%80%E5%8D%9A%E6%89%93%E5%8D%B0%E6%9D%90%E6%96%99",
      flagship: "彩色 PETG（1kg/1.75mm，韧性稳定）、3D 打印耗材批发；以拼多多超低价著称",
      reputation: "拼多多渠道的高性价比耗材品牌，1kg 彩色 PETG 曾做到 17.68 元（2025-11 中关村在线导购记录），主打批发与低价走量",
      materials: ["PETG", "彩色 PETG", "批发耗材"],
      sourceUrls: ["https://oa.zol.com.cn/1083/10839374.html"]
    },
    {
      id: "kaaber", nameCn: "Kaaber", nameEn: "Kaaber", icon: "🐯",
      hq: "中国（平台：淘宝）", url: "https://world.taobao.com/item/891819328322.htm",
      flagship: "PLA Basic（新手友好入门级，约 40 元/卷 1kg 装）",
      reputation: "什么值得买测评推荐的新手入门品牌：PLA Basic 性价比突出（约 40 元/卷），常规 200℃ 打印稳定，适合预算有限的入门用户",
      materials: ["PLA Basic", "PLA"],
      sourceUrls: ["https://post.smzdm.com/talk/p/avvlo384/", "https://post.smzdm.com/talk/p/a2qldvnq/"]
    },
    {
      id: "yixiang", nameCn: "以祥", nameEn: "Yixiang / YASIN（东莞以祥三维科技）", icon: "🏭",
      hq: "中国东莞", url: "https://s.taobao.com/search?q=%E4%BB%A5%E7%A5%A5%203D%E6%89%93%E5%8D%B0%E6%9D%90%E6%96%99",
      flagship: "PLA（0.5/1KG，1.75/2.85/3.0mm 多规格）、进口 ABS、HIPS、打印笔耗材；早期 3D 打印材料厂商",
      reputation: "东莞市以祥三维科技有限公司（YASIN），老牌耗材厂商：覆盖 1.75/2.85/3.0mm 多线径与打印笔耗材，曾收录于打印派商城（PLA 55.5 元/ABS 46.5 元）",
      materials: ["PLA", "ABS", "HIPS", "打印笔耗材"],
      sourceUrls: ["http://wap.dayinpai.com", "https://world.taobao.com/item/579215673817.htm"]
    }
  ]
};
